/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './toplist';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from 'ionic-angular/components/list/list';
import * as import16 from 'ionic-angular/components/item/item';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from 'ionic-angular/config/config';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from 'ionic-angular/navigation/view-controller';
import * as import21 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import22 from 'ionic-angular/components/app/app';
import * as import23 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import25 from 'ionic-angular/util/keyboard';
import * as import26 from '@angular/core/src/zone/ng_zone';
import * as import27 from 'ionic-angular/components/tabs/tabs';
import * as import28 from 'ionic-angular/gestures/gesture-controller';
import * as import29 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import30 from 'ionic-angular/util/form';
var renderType_ToplistPage_Host:import0.RenderComponentType = (null as any);
class _View_ToplistPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ToplistPage_0_4:import3.ToplistPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ToplistPage_Host0,renderType_ToplistPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ToplistPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ToplistPage_0_4 = new import3.ToplistPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._ToplistPage_0_4,[],compView_0);
    compView_0.create(this._ToplistPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ToplistPage) && (0 === requestNodeIndex))) { return this._ToplistPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ToplistPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ToplistPage_Host === (null as any))) { (renderType_ToplistPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ToplistPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ToplistPageNgFactory:import10.ComponentFactory<import3.ToplistPage> = new import10.ComponentFactory<import3.ToplistPage>('ng-component',viewFactory_ToplistPage_Host0,import3.ToplistPage);
const styles_ToplistPage:any[] = [];
var renderType_ToplistPage:import0.RenderComponentType = (null as any);
class _View_ToplistPage0 extends import1.AppView<import3.ToplistPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import12.Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _ToolbarTitle_5_4:import13.ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _Content_10_4:import14.Content;
  _text_11:any;
  _el_12:any;
  _List_12_3:import15.List;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Item_14_4:import16.Item;
  _ItemContent_14_5:import16.ItemContent;
  _query_Label_14_0:import17.QueryList<any>;
  _query_Button_14_1:import17.QueryList<any>;
  _query_Icon_14_2:import17.QueryList<any>;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Item_17_4:import16.Item;
  _ItemContent_17_5:import16.ItemContent;
  _query_Label_17_0:import17.QueryList<any>;
  _query_Button_17_1:import17.QueryList<any>;
  _query_Icon_17_2:import17.QueryList<any>;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _Item_20_4:import16.Item;
  _ItemContent_20_5:import16.ItemContent;
  _query_Label_20_0:import17.QueryList<any>;
  _query_Button_20_1:import17.QueryList<any>;
  _query_Icon_20_2:import17.QueryList<any>;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Item_23_4:import16.Item;
  _ItemContent_23_5:import16.ItemContent;
  _query_Label_23_0:import17.QueryList<any>;
  _query_Button_23_1:import17.QueryList<any>;
  _query_Icon_23_2:import17.QueryList<any>;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _Item_26_4:import16.Item;
  _ItemContent_26_5:import16.ItemContent;
  _query_Label_26_0:import17.QueryList<any>;
  _query_Button_26_1:import17.QueryList<any>;
  _query_Icon_26_2:import17.QueryList<any>;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _Item_29_4:import16.Item;
  _ItemContent_29_5:import16.ItemContent;
  _query_Label_29_0:import17.QueryList<any>;
  _query_Button_29_1:import17.QueryList<any>;
  _query_Icon_29_2:import17.QueryList<any>;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _Item_32_4:import16.Item;
  _ItemContent_32_5:import16.ItemContent;
  _query_Label_32_0:import17.QueryList<any>;
  _query_Button_32_1:import17.QueryList<any>;
  _query_Icon_32_2:import17.QueryList<any>;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _Item_35_4:import16.Item;
  _ItemContent_35_5:import16.ItemContent;
  _query_Label_35_0:import17.QueryList<any>;
  _query_Button_35_1:import17.QueryList<any>;
  _query_Icon_35_2:import17.QueryList<any>;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _Item_38_4:import16.Item;
  _ItemContent_38_5:import16.ItemContent;
  _query_Label_38_0:import17.QueryList<any>;
  _query_Button_38_1:import17.QueryList<any>;
  _query_Icon_38_2:import17.QueryList<any>;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _Item_41_4:import16.Item;
  _ItemContent_41_5:import16.ItemContent;
  _query_Label_41_0:import17.QueryList<any>;
  _query_Button_41_1:import17.QueryList<any>;
  _query_Icon_41_2:import17.QueryList<any>;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import2.AppElement;
  _Item_44_4:import16.Item;
  _ItemContent_44_5:import16.ItemContent;
  _query_Label_44_0:import17.QueryList<any>;
  _query_Button_44_1:import17.QueryList<any>;
  _query_Icon_44_2:import17.QueryList<any>;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _Item_47_4:import16.Item;
  _ItemContent_47_5:import16.ItemContent;
  _query_Label_47_0:import17.QueryList<any>;
  _query_Button_47_1:import17.QueryList<any>;
  _query_Icon_47_2:import17.QueryList<any>;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import2.AppElement;
  _Item_50_4:import16.Item;
  _ItemContent_50_5:import16.ItemContent;
  _query_Label_50_0:import17.QueryList<any>;
  _query_Button_50_1:import17.QueryList<any>;
  _query_Icon_50_2:import17.QueryList<any>;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  /*private*/ _appEl_53:import2.AppElement;
  _Item_53_4:import16.Item;
  _ItemContent_53_5:import16.ItemContent;
  _query_Label_53_0:import17.QueryList<any>;
  _query_Button_53_1:import17.QueryList<any>;
  _query_Icon_53_2:import17.QueryList<any>;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  /*private*/ _appEl_56:import2.AppElement;
  _Item_56_4:import16.Item;
  _ItemContent_56_5:import16.ItemContent;
  _query_Label_56_0:import17.QueryList<any>;
  _query_Button_56_1:import17.QueryList<any>;
  _query_Icon_56_2:import17.QueryList<any>;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  /*private*/ _appEl_59:import2.AppElement;
  _Item_59_4:import16.Item;
  _ItemContent_59_5:import16.ItemContent;
  _query_Label_59_0:import17.QueryList<any>;
  _query_Button_59_1:import17.QueryList<any>;
  _query_Icon_59_2:import17.QueryList<any>;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  /*private*/ _appEl_62:import2.AppElement;
  _Item_62_4:import16.Item;
  _ItemContent_62_5:import16.ItemContent;
  _query_Label_62_0:import17.QueryList<any>;
  _query_Button_62_1:import17.QueryList<any>;
  _query_Icon_62_2:import17.QueryList<any>;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  /*private*/ _appEl_65:import2.AppElement;
  _Item_65_4:import16.Item;
  _ItemContent_65_5:import16.ItemContent;
  _query_Label_65_0:import17.QueryList<any>;
  _query_Button_65_1:import17.QueryList<any>;
  _query_Icon_65_2:import17.QueryList<any>;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  /*private*/ _appEl_68:import2.AppElement;
  _Item_68_4:import16.Item;
  _ItemContent_68_5:import16.ItemContent;
  _query_Label_68_0:import17.QueryList<any>;
  _query_Button_68_1:import17.QueryList<any>;
  _query_Icon_68_2:import17.QueryList<any>;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  /*private*/ _appEl_71:import2.AppElement;
  _Item_71_4:import16.Item;
  _ItemContent_71_5:import16.ItemContent;
  _query_Label_71_0:import17.QueryList<any>;
  _query_Button_71_1:import17.QueryList<any>;
  _query_Icon_71_2:import17.QueryList<any>;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  /*private*/ _appEl_74:import2.AppElement;
  _Item_74_4:import16.Item;
  _ItemContent_74_5:import16.ItemContent;
  _query_Label_74_0:import17.QueryList<any>;
  _query_Button_74_1:import17.QueryList<any>;
  _query_Icon_74_2:import17.QueryList<any>;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  /*private*/ _appEl_77:import2.AppElement;
  _Item_77_4:import16.Item;
  _ItemContent_77_5:import16.ItemContent;
  _query_Label_77_0:import17.QueryList<any>;
  _query_Button_77_1:import17.QueryList<any>;
  _query_Icon_77_2:import17.QueryList<any>;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  /*private*/ _appEl_80:import2.AppElement;
  _Item_80_4:import16.Item;
  _ItemContent_80_5:import16.ItemContent;
  _query_Label_80_0:import17.QueryList<any>;
  _query_Button_80_1:import17.QueryList<any>;
  _query_Icon_80_2:import17.QueryList<any>;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  /*private*/ _appEl_83:import2.AppElement;
  _Item_83_4:import16.Item;
  _ItemContent_83_5:import16.ItemContent;
  _query_Label_83_0:import17.QueryList<any>;
  _query_Button_83_1:import17.QueryList<any>;
  _query_Icon_83_2:import17.QueryList<any>;
  _text_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ToplistPage0,renderType_ToplistPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Header(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import20.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import21.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Navbar(this.parentInjector.get(import22.App),this.parentInjector.get(import20.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,[],compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import2.AppElement(5,3,this,this._el_5);
    var compView_5:any = import23.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import13.ToolbarTitle(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_3_4);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'Toplista',(null as any));
    compView_5.create(this._ToolbarTitle_5_4,[[].concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4,[
      [],
      [],
      [],
      [].concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','toplist');
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import2.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import24.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import14.Content(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import22.App),this.parentInjector.get(import25.Keyboard),this.parentInjector.get(import26.NgZone),this.parentInjector.get(import20.ViewController,(null as any)),this.parentInjector.get(import27.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4,[],compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_12_3 = new import15.List(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import28.GestureController));
    this._text_13 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','item item-block');
    this._appEl_14 = new import2.AppElement(14,12,this,this._el_14);
    var compView_14:any = import29.viewFactory_Item0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Item_14_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_14),this.renderer);
    this._ItemContent_14_5 = new import16.ItemContent();
    this._query_Label_14_0 = new import17.QueryList<any>();
    this._query_Button_14_1 = new import17.QueryList<any>();
    this._query_Icon_14_2 = new import17.QueryList<any>();
    this._appEl_14.initComponent(this._Item_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n    Jack Sparrow\n  ',(null as any));
    this._query_Label_14_0.reset([]);
    this._Item_14_4.contentLabel = this._query_Label_14_0.first;
    compView_14.create(this._Item_14_4,[
      [],
      [],
      [].concat([this._text_15]),
      [],
      []
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','item item-block');
    this._appEl_17 = new import2.AppElement(17,12,this,this._el_17);
    var compView_17:any = import29.viewFactory_Item0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Item_17_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_17),this.renderer);
    this._ItemContent_17_5 = new import16.ItemContent();
    this._query_Label_17_0 = new import17.QueryList<any>();
    this._query_Button_17_1 = new import17.QueryList<any>();
    this._query_Icon_17_2 = new import17.QueryList<any>();
    this._appEl_17.initComponent(this._Item_17_4,[],compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n    Luke Skywalker\n  ',(null as any));
    this._query_Label_17_0.reset([]);
    this._Item_17_4.contentLabel = this._query_Label_17_0.first;
    compView_17.create(this._Item_17_4,[
      [],
      [],
      [].concat([this._text_18]),
      [],
      []
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','item item-block');
    this._appEl_20 = new import2.AppElement(20,12,this,this._el_20);
    var compView_20:any = import29.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_20),this.renderer);
    this._ItemContent_20_5 = new import16.ItemContent();
    this._query_Label_20_0 = new import17.QueryList<any>();
    this._query_Button_20_1 = new import17.QueryList<any>();
    this._query_Icon_20_2 = new import17.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n    Harry Potter\n  ',(null as any));
    this._query_Label_20_0.reset([]);
    this._Item_20_4.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4,[
      [],
      [],
      [].concat([this._text_21]),
      [],
      []
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this._appEl_23 = new import2.AppElement(23,12,this,this._el_23);
    var compView_23:any = import29.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_23),this.renderer);
    this._ItemContent_23_5 = new import16.ItemContent();
    this._query_Label_23_0 = new import17.QueryList<any>();
    this._query_Button_23_1 = new import17.QueryList<any>();
    this._query_Icon_23_2 = new import17.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n    Edward Cullen\n  ',(null as any));
    this._query_Label_23_0.reset([]);
    this._Item_23_4.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4,[
      [],
      [],
      [].concat([this._text_24]),
      [],
      []
    ]
    ,(null as any));
    this._text_25 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','item item-block');
    this._appEl_26 = new import2.AppElement(26,12,this,this._el_26);
    var compView_26:any = import29.viewFactory_Item0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Item_26_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_26),this.renderer);
    this._ItemContent_26_5 = new import16.ItemContent();
    this._query_Label_26_0 = new import17.QueryList<any>();
    this._query_Button_26_1 = new import17.QueryList<any>();
    this._query_Icon_26_2 = new import17.QueryList<any>();
    this._appEl_26.initComponent(this._Item_26_4,[],compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n    The Mask\n  ',(null as any));
    this._query_Label_26_0.reset([]);
    this._Item_26_4.contentLabel = this._query_Label_26_0.first;
    compView_26.create(this._Item_26_4,[
      [],
      [],
      [].concat([this._text_27]),
      [],
      []
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','item item-block');
    this._appEl_29 = new import2.AppElement(29,12,this,this._el_29);
    var compView_29:any = import29.viewFactory_Item0(this.viewUtils,this.injector(29),this._appEl_29);
    this._Item_29_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_29),this.renderer);
    this._ItemContent_29_5 = new import16.ItemContent();
    this._query_Label_29_0 = new import17.QueryList<any>();
    this._query_Button_29_1 = new import17.QueryList<any>();
    this._query_Icon_29_2 = new import17.QueryList<any>();
    this._appEl_29.initComponent(this._Item_29_4,[],compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n    Spiderman\n  ',(null as any));
    this._query_Label_29_0.reset([]);
    this._Item_29_4.contentLabel = this._query_Label_29_0.first;
    compView_29.create(this._Item_29_4,[
      [],
      [],
      [].concat([this._text_30]),
      [],
      []
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','item item-block');
    this._appEl_32 = new import2.AppElement(32,12,this,this._el_32);
    var compView_32:any = import29.viewFactory_Item0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Item_32_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_32),this.renderer);
    this._ItemContent_32_5 = new import16.ItemContent();
    this._query_Label_32_0 = new import17.QueryList<any>();
    this._query_Button_32_1 = new import17.QueryList<any>();
    this._query_Icon_32_2 = new import17.QueryList<any>();
    this._appEl_32.initComponent(this._Item_32_4,[],compView_32);
    this._text_33 = this.renderer.createText((null as any),'\n    Tor\n  ',(null as any));
    this._query_Label_32_0.reset([]);
    this._Item_32_4.contentLabel = this._query_Label_32_0.first;
    compView_32.create(this._Item_32_4,[
      [],
      [],
      [].concat([this._text_33]),
      [],
      []
    ]
    ,(null as any));
    this._text_34 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','item item-block');
    this._appEl_35 = new import2.AppElement(35,12,this,this._el_35);
    var compView_35:any = import29.viewFactory_Item0(this.viewUtils,this.injector(35),this._appEl_35);
    this._Item_35_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_35),this.renderer);
    this._ItemContent_35_5 = new import16.ItemContent();
    this._query_Label_35_0 = new import17.QueryList<any>();
    this._query_Button_35_1 = new import17.QueryList<any>();
    this._query_Icon_35_2 = new import17.QueryList<any>();
    this._appEl_35.initComponent(this._Item_35_4,[],compView_35);
    this._text_36 = this.renderer.createText((null as any),'\n    Lille Skutt\n  ',(null as any));
    this._query_Label_35_0.reset([]);
    this._Item_35_4.contentLabel = this._query_Label_35_0.first;
    compView_35.create(this._Item_35_4,[
      [],
      [],
      [].concat([this._text_36]),
      [],
      []
    ]
    ,(null as any));
    this._text_37 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','item item-block');
    this._appEl_38 = new import2.AppElement(38,12,this,this._el_38);
    var compView_38:any = import29.viewFactory_Item0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Item_38_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_38),this.renderer);
    this._ItemContent_38_5 = new import16.ItemContent();
    this._query_Label_38_0 = new import17.QueryList<any>();
    this._query_Button_38_1 = new import17.QueryList<any>();
    this._query_Icon_38_2 = new import17.QueryList<any>();
    this._appEl_38.initComponent(this._Item_38_4,[],compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n    Jack Sparrow\n  ',(null as any));
    this._query_Label_38_0.reset([]);
    this._Item_38_4.contentLabel = this._query_Label_38_0.first;
    compView_38.create(this._Item_38_4,[
      [],
      [],
      [].concat([this._text_39]),
      [],
      []
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','item item-block');
    this._appEl_41 = new import2.AppElement(41,12,this,this._el_41);
    var compView_41:any = import29.viewFactory_Item0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Item_41_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_41),this.renderer);
    this._ItemContent_41_5 = new import16.ItemContent();
    this._query_Label_41_0 = new import17.QueryList<any>();
    this._query_Button_41_1 = new import17.QueryList<any>();
    this._query_Icon_41_2 = new import17.QueryList<any>();
    this._appEl_41.initComponent(this._Item_41_4,[],compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n    Luke Skywalker\n  ',(null as any));
    this._query_Label_41_0.reset([]);
    this._Item_41_4.contentLabel = this._query_Label_41_0.first;
    compView_41.create(this._Item_41_4,[
      [],
      [],
      [].concat([this._text_42]),
      [],
      []
    ]
    ,(null as any));
    this._text_43 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','item item-block');
    this._appEl_44 = new import2.AppElement(44,12,this,this._el_44);
    var compView_44:any = import29.viewFactory_Item0(this.viewUtils,this.injector(44),this._appEl_44);
    this._Item_44_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_44),this.renderer);
    this._ItemContent_44_5 = new import16.ItemContent();
    this._query_Label_44_0 = new import17.QueryList<any>();
    this._query_Button_44_1 = new import17.QueryList<any>();
    this._query_Icon_44_2 = new import17.QueryList<any>();
    this._appEl_44.initComponent(this._Item_44_4,[],compView_44);
    this._text_45 = this.renderer.createText((null as any),'\n    Harry Potter\n  ',(null as any));
    this._query_Label_44_0.reset([]);
    this._Item_44_4.contentLabel = this._query_Label_44_0.first;
    compView_44.create(this._Item_44_4,[
      [],
      [],
      [].concat([this._text_45]),
      [],
      []
    ]
    ,(null as any));
    this._text_46 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','item item-block');
    this._appEl_47 = new import2.AppElement(47,12,this,this._el_47);
    var compView_47:any = import29.viewFactory_Item0(this.viewUtils,this.injector(47),this._appEl_47);
    this._Item_47_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_47),this.renderer);
    this._ItemContent_47_5 = new import16.ItemContent();
    this._query_Label_47_0 = new import17.QueryList<any>();
    this._query_Button_47_1 = new import17.QueryList<any>();
    this._query_Icon_47_2 = new import17.QueryList<any>();
    this._appEl_47.initComponent(this._Item_47_4,[],compView_47);
    this._text_48 = this.renderer.createText((null as any),'\n    Edward Cullen\n  ',(null as any));
    this._query_Label_47_0.reset([]);
    this._Item_47_4.contentLabel = this._query_Label_47_0.first;
    compView_47.create(this._Item_47_4,[
      [],
      [],
      [].concat([this._text_48]),
      [],
      []
    ]
    ,(null as any));
    this._text_49 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','item item-block');
    this._appEl_50 = new import2.AppElement(50,12,this,this._el_50);
    var compView_50:any = import29.viewFactory_Item0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Item_50_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_50),this.renderer);
    this._ItemContent_50_5 = new import16.ItemContent();
    this._query_Label_50_0 = new import17.QueryList<any>();
    this._query_Button_50_1 = new import17.QueryList<any>();
    this._query_Icon_50_2 = new import17.QueryList<any>();
    this._appEl_50.initComponent(this._Item_50_4,[],compView_50);
    this._text_51 = this.renderer.createText((null as any),'\n    The Mask\n  ',(null as any));
    this._query_Label_50_0.reset([]);
    this._Item_50_4.contentLabel = this._query_Label_50_0.first;
    compView_50.create(this._Item_50_4,[
      [],
      [],
      [].concat([this._text_51]),
      [],
      []
    ]
    ,(null as any));
    this._text_52 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','item item-block');
    this._appEl_53 = new import2.AppElement(53,12,this,this._el_53);
    var compView_53:any = import29.viewFactory_Item0(this.viewUtils,this.injector(53),this._appEl_53);
    this._Item_53_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_53),this.renderer);
    this._ItemContent_53_5 = new import16.ItemContent();
    this._query_Label_53_0 = new import17.QueryList<any>();
    this._query_Button_53_1 = new import17.QueryList<any>();
    this._query_Icon_53_2 = new import17.QueryList<any>();
    this._appEl_53.initComponent(this._Item_53_4,[],compView_53);
    this._text_54 = this.renderer.createText((null as any),'\n    Spiderman\n  ',(null as any));
    this._query_Label_53_0.reset([]);
    this._Item_53_4.contentLabel = this._query_Label_53_0.first;
    compView_53.create(this._Item_53_4,[
      [],
      [],
      [].concat([this._text_54]),
      [],
      []
    ]
    ,(null as any));
    this._text_55 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','item item-block');
    this._appEl_56 = new import2.AppElement(56,12,this,this._el_56);
    var compView_56:any = import29.viewFactory_Item0(this.viewUtils,this.injector(56),this._appEl_56);
    this._Item_56_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_56),this.renderer);
    this._ItemContent_56_5 = new import16.ItemContent();
    this._query_Label_56_0 = new import17.QueryList<any>();
    this._query_Button_56_1 = new import17.QueryList<any>();
    this._query_Icon_56_2 = new import17.QueryList<any>();
    this._appEl_56.initComponent(this._Item_56_4,[],compView_56);
    this._text_57 = this.renderer.createText((null as any),'\n    Tor\n  ',(null as any));
    this._query_Label_56_0.reset([]);
    this._Item_56_4.contentLabel = this._query_Label_56_0.first;
    compView_56.create(this._Item_56_4,[
      [],
      [],
      [].concat([this._text_57]),
      [],
      []
    ]
    ,(null as any));
    this._text_58 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','item item-block');
    this._appEl_59 = new import2.AppElement(59,12,this,this._el_59);
    var compView_59:any = import29.viewFactory_Item0(this.viewUtils,this.injector(59),this._appEl_59);
    this._Item_59_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_59),this.renderer);
    this._ItemContent_59_5 = new import16.ItemContent();
    this._query_Label_59_0 = new import17.QueryList<any>();
    this._query_Button_59_1 = new import17.QueryList<any>();
    this._query_Icon_59_2 = new import17.QueryList<any>();
    this._appEl_59.initComponent(this._Item_59_4,[],compView_59);
    this._text_60 = this.renderer.createText((null as any),'\n    Lille Skutt\n  ',(null as any));
    this._query_Label_59_0.reset([]);
    this._Item_59_4.contentLabel = this._query_Label_59_0.first;
    compView_59.create(this._Item_59_4,[
      [],
      [],
      [].concat([this._text_60]),
      [],
      []
    ]
    ,(null as any));
    this._text_61 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','item item-block');
    this._appEl_62 = new import2.AppElement(62,12,this,this._el_62);
    var compView_62:any = import29.viewFactory_Item0(this.viewUtils,this.injector(62),this._appEl_62);
    this._Item_62_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_62),this.renderer);
    this._ItemContent_62_5 = new import16.ItemContent();
    this._query_Label_62_0 = new import17.QueryList<any>();
    this._query_Button_62_1 = new import17.QueryList<any>();
    this._query_Icon_62_2 = new import17.QueryList<any>();
    this._appEl_62.initComponent(this._Item_62_4,[],compView_62);
    this._text_63 = this.renderer.createText((null as any),'\n    Jack Sparrow\n  ',(null as any));
    this._query_Label_62_0.reset([]);
    this._Item_62_4.contentLabel = this._query_Label_62_0.first;
    compView_62.create(this._Item_62_4,[
      [],
      [],
      [].concat([this._text_63]),
      [],
      []
    ]
    ,(null as any));
    this._text_64 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_65,'class','item item-block');
    this._appEl_65 = new import2.AppElement(65,12,this,this._el_65);
    var compView_65:any = import29.viewFactory_Item0(this.viewUtils,this.injector(65),this._appEl_65);
    this._Item_65_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_65),this.renderer);
    this._ItemContent_65_5 = new import16.ItemContent();
    this._query_Label_65_0 = new import17.QueryList<any>();
    this._query_Button_65_1 = new import17.QueryList<any>();
    this._query_Icon_65_2 = new import17.QueryList<any>();
    this._appEl_65.initComponent(this._Item_65_4,[],compView_65);
    this._text_66 = this.renderer.createText((null as any),'\n    Luke Skywalker\n  ',(null as any));
    this._query_Label_65_0.reset([]);
    this._Item_65_4.contentLabel = this._query_Label_65_0.first;
    compView_65.create(this._Item_65_4,[
      [],
      [],
      [].concat([this._text_66]),
      [],
      []
    ]
    ,(null as any));
    this._text_67 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','item item-block');
    this._appEl_68 = new import2.AppElement(68,12,this,this._el_68);
    var compView_68:any = import29.viewFactory_Item0(this.viewUtils,this.injector(68),this._appEl_68);
    this._Item_68_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_68),this.renderer);
    this._ItemContent_68_5 = new import16.ItemContent();
    this._query_Label_68_0 = new import17.QueryList<any>();
    this._query_Button_68_1 = new import17.QueryList<any>();
    this._query_Icon_68_2 = new import17.QueryList<any>();
    this._appEl_68.initComponent(this._Item_68_4,[],compView_68);
    this._text_69 = this.renderer.createText((null as any),'\n    Harry Potter\n  ',(null as any));
    this._query_Label_68_0.reset([]);
    this._Item_68_4.contentLabel = this._query_Label_68_0.first;
    compView_68.create(this._Item_68_4,[
      [],
      [],
      [].concat([this._text_69]),
      [],
      []
    ]
    ,(null as any));
    this._text_70 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_71 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_71,'class','item item-block');
    this._appEl_71 = new import2.AppElement(71,12,this,this._el_71);
    var compView_71:any = import29.viewFactory_Item0(this.viewUtils,this.injector(71),this._appEl_71);
    this._Item_71_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_71),this.renderer);
    this._ItemContent_71_5 = new import16.ItemContent();
    this._query_Label_71_0 = new import17.QueryList<any>();
    this._query_Button_71_1 = new import17.QueryList<any>();
    this._query_Icon_71_2 = new import17.QueryList<any>();
    this._appEl_71.initComponent(this._Item_71_4,[],compView_71);
    this._text_72 = this.renderer.createText((null as any),'\n    Edward Cullen\n  ',(null as any));
    this._query_Label_71_0.reset([]);
    this._Item_71_4.contentLabel = this._query_Label_71_0.first;
    compView_71.create(this._Item_71_4,[
      [],
      [],
      [].concat([this._text_72]),
      [],
      []
    ]
    ,(null as any));
    this._text_73 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_74,'class','item item-block');
    this._appEl_74 = new import2.AppElement(74,12,this,this._el_74);
    var compView_74:any = import29.viewFactory_Item0(this.viewUtils,this.injector(74),this._appEl_74);
    this._Item_74_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_74),this.renderer);
    this._ItemContent_74_5 = new import16.ItemContent();
    this._query_Label_74_0 = new import17.QueryList<any>();
    this._query_Button_74_1 = new import17.QueryList<any>();
    this._query_Icon_74_2 = new import17.QueryList<any>();
    this._appEl_74.initComponent(this._Item_74_4,[],compView_74);
    this._text_75 = this.renderer.createText((null as any),'\n    The Mask\n  ',(null as any));
    this._query_Label_74_0.reset([]);
    this._Item_74_4.contentLabel = this._query_Label_74_0.first;
    compView_74.create(this._Item_74_4,[
      [],
      [],
      [].concat([this._text_75]),
      [],
      []
    ]
    ,(null as any));
    this._text_76 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_77 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_77,'class','item item-block');
    this._appEl_77 = new import2.AppElement(77,12,this,this._el_77);
    var compView_77:any = import29.viewFactory_Item0(this.viewUtils,this.injector(77),this._appEl_77);
    this._Item_77_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_77),this.renderer);
    this._ItemContent_77_5 = new import16.ItemContent();
    this._query_Label_77_0 = new import17.QueryList<any>();
    this._query_Button_77_1 = new import17.QueryList<any>();
    this._query_Icon_77_2 = new import17.QueryList<any>();
    this._appEl_77.initComponent(this._Item_77_4,[],compView_77);
    this._text_78 = this.renderer.createText((null as any),'\n    Spiderman\n  ',(null as any));
    this._query_Label_77_0.reset([]);
    this._Item_77_4.contentLabel = this._query_Label_77_0.first;
    compView_77.create(this._Item_77_4,[
      [],
      [],
      [].concat([this._text_78]),
      [],
      []
    ]
    ,(null as any));
    this._text_79 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','item item-block');
    this._appEl_80 = new import2.AppElement(80,12,this,this._el_80);
    var compView_80:any = import29.viewFactory_Item0(this.viewUtils,this.injector(80),this._appEl_80);
    this._Item_80_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_80),this.renderer);
    this._ItemContent_80_5 = new import16.ItemContent();
    this._query_Label_80_0 = new import17.QueryList<any>();
    this._query_Button_80_1 = new import17.QueryList<any>();
    this._query_Icon_80_2 = new import17.QueryList<any>();
    this._appEl_80.initComponent(this._Item_80_4,[],compView_80);
    this._text_81 = this.renderer.createText((null as any),'\n    Tor\n  ',(null as any));
    this._query_Label_80_0.reset([]);
    this._Item_80_4.contentLabel = this._query_Label_80_0.first;
    compView_80.create(this._Item_80_4,[
      [],
      [],
      [].concat([this._text_81]),
      [],
      []
    ]
    ,(null as any));
    this._text_82 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._el_83 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_83,'class','item item-block');
    this._appEl_83 = new import2.AppElement(83,12,this,this._el_83);
    var compView_83:any = import29.viewFactory_Item0(this.viewUtils,this.injector(83),this._appEl_83);
    this._Item_83_4 = new import16.Item(this.parentInjector.get(import30.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_83),this.renderer);
    this._ItemContent_83_5 = new import16.ItemContent();
    this._query_Label_83_0 = new import17.QueryList<any>();
    this._query_Button_83_1 = new import17.QueryList<any>();
    this._query_Icon_83_2 = new import17.QueryList<any>();
    this._appEl_83.initComponent(this._Item_83_4,[],compView_83);
    this._text_84 = this.renderer.createText((null as any),'\n    Lille Skutt\n  ',(null as any));
    this._query_Label_83_0.reset([]);
    this._Item_83_4.contentLabel = this._query_Label_83_0.first;
    compView_83.create(this._Item_83_4,[
      [],
      [],
      [].concat([this._text_84]),
      [],
      []
    ]
    ,(null as any));
    this._text_85 = this.renderer.createText(this._el_12,'\n',(null as any));
    this._text_86 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_10.create(this._Content_10_4,[
      [],
      [].concat([
        this._text_11,
        this._el_12,
        this._text_86
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_87 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._text_86,
      this._text_87
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4; }
    if (((token === import12.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4; }
    if (((token === import11.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3; }
    if (((token === import16.Item) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Item_14_4; }
    if (((token === import16.ItemContent) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ItemContent_14_5; }
    if (((token === import16.Item) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Item_17_4; }
    if (((token === import16.ItemContent) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ItemContent_17_5; }
    if (((token === import16.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_20_4; }
    if (((token === import16.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_20_5; }
    if (((token === import16.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Item_23_4; }
    if (((token === import16.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._ItemContent_23_5; }
    if (((token === import16.Item) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Item_26_4; }
    if (((token === import16.ItemContent) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ItemContent_26_5; }
    if (((token === import16.Item) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Item_29_4; }
    if (((token === import16.ItemContent) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ItemContent_29_5; }
    if (((token === import16.Item) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Item_32_4; }
    if (((token === import16.ItemContent) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._ItemContent_32_5; }
    if (((token === import16.Item) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Item_35_4; }
    if (((token === import16.ItemContent) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._ItemContent_35_5; }
    if (((token === import16.Item) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Item_38_4; }
    if (((token === import16.ItemContent) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ItemContent_38_5; }
    if (((token === import16.Item) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Item_41_4; }
    if (((token === import16.ItemContent) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._ItemContent_41_5; }
    if (((token === import16.Item) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Item_44_4; }
    if (((token === import16.ItemContent) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._ItemContent_44_5; }
    if (((token === import16.Item) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Item_47_4; }
    if (((token === import16.ItemContent) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._ItemContent_47_5; }
    if (((token === import16.Item) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Item_50_4; }
    if (((token === import16.ItemContent) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._ItemContent_50_5; }
    if (((token === import16.Item) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Item_53_4; }
    if (((token === import16.ItemContent) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._ItemContent_53_5; }
    if (((token === import16.Item) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Item_56_4; }
    if (((token === import16.ItemContent) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._ItemContent_56_5; }
    if (((token === import16.Item) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Item_59_4; }
    if (((token === import16.ItemContent) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._ItemContent_59_5; }
    if (((token === import16.Item) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Item_62_4; }
    if (((token === import16.ItemContent) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._ItemContent_62_5; }
    if (((token === import16.Item) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Item_65_4; }
    if (((token === import16.ItemContent) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._ItemContent_65_5; }
    if (((token === import16.Item) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Item_68_4; }
    if (((token === import16.ItemContent) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._ItemContent_68_5; }
    if (((token === import16.Item) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._Item_71_4; }
    if (((token === import16.ItemContent) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._ItemContent_71_5; }
    if (((token === import16.Item) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._Item_74_4; }
    if (((token === import16.ItemContent) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._ItemContent_74_5; }
    if (((token === import16.Item) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._Item_77_4; }
    if (((token === import16.ItemContent) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._ItemContent_77_5; }
    if (((token === import16.Item) && ((80 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._Item_80_4; }
    if (((token === import16.ItemContent) && ((80 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._ItemContent_80_5; }
    if (((token === import16.Item) && ((83 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._Item_83_4; }
    if (((token === import16.ItemContent) && ((83 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._ItemContent_83_5; }
    if (((token === import15.List) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 85)))) { return this._List_12_3; }
    if (((token === import14.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._Content_10_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_10_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_14_1.dirty) {
        this._query_Button_14_1.reset([]);
        this._Item_14_4._buttons = this._query_Button_14_1;
        this._query_Button_14_1.notifyOnChanges();
      }
      if (this._query_Icon_14_2.dirty) {
        this._query_Icon_14_2.reset([]);
        this._Item_14_4._icons = this._query_Icon_14_2;
        this._query_Icon_14_2.notifyOnChanges();
      }
      if (this._query_Button_17_1.dirty) {
        this._query_Button_17_1.reset([]);
        this._Item_17_4._buttons = this._query_Button_17_1;
        this._query_Button_17_1.notifyOnChanges();
      }
      if (this._query_Icon_17_2.dirty) {
        this._query_Icon_17_2.reset([]);
        this._Item_17_4._icons = this._query_Icon_17_2;
        this._query_Icon_17_2.notifyOnChanges();
      }
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset([]);
        this._Item_20_4._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset([]);
        this._Item_20_4._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset([]);
        this._Item_23_4._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset([]);
        this._Item_23_4._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_26_1.dirty) {
        this._query_Button_26_1.reset([]);
        this._Item_26_4._buttons = this._query_Button_26_1;
        this._query_Button_26_1.notifyOnChanges();
      }
      if (this._query_Icon_26_2.dirty) {
        this._query_Icon_26_2.reset([]);
        this._Item_26_4._icons = this._query_Icon_26_2;
        this._query_Icon_26_2.notifyOnChanges();
      }
      if (this._query_Button_29_1.dirty) {
        this._query_Button_29_1.reset([]);
        this._Item_29_4._buttons = this._query_Button_29_1;
        this._query_Button_29_1.notifyOnChanges();
      }
      if (this._query_Icon_29_2.dirty) {
        this._query_Icon_29_2.reset([]);
        this._Item_29_4._icons = this._query_Icon_29_2;
        this._query_Icon_29_2.notifyOnChanges();
      }
      if (this._query_Button_32_1.dirty) {
        this._query_Button_32_1.reset([]);
        this._Item_32_4._buttons = this._query_Button_32_1;
        this._query_Button_32_1.notifyOnChanges();
      }
      if (this._query_Icon_32_2.dirty) {
        this._query_Icon_32_2.reset([]);
        this._Item_32_4._icons = this._query_Icon_32_2;
        this._query_Icon_32_2.notifyOnChanges();
      }
      if (this._query_Button_35_1.dirty) {
        this._query_Button_35_1.reset([]);
        this._Item_35_4._buttons = this._query_Button_35_1;
        this._query_Button_35_1.notifyOnChanges();
      }
      if (this._query_Icon_35_2.dirty) {
        this._query_Icon_35_2.reset([]);
        this._Item_35_4._icons = this._query_Icon_35_2;
        this._query_Icon_35_2.notifyOnChanges();
      }
      if (this._query_Button_38_1.dirty) {
        this._query_Button_38_1.reset([]);
        this._Item_38_4._buttons = this._query_Button_38_1;
        this._query_Button_38_1.notifyOnChanges();
      }
      if (this._query_Icon_38_2.dirty) {
        this._query_Icon_38_2.reset([]);
        this._Item_38_4._icons = this._query_Icon_38_2;
        this._query_Icon_38_2.notifyOnChanges();
      }
      if (this._query_Button_41_1.dirty) {
        this._query_Button_41_1.reset([]);
        this._Item_41_4._buttons = this._query_Button_41_1;
        this._query_Button_41_1.notifyOnChanges();
      }
      if (this._query_Icon_41_2.dirty) {
        this._query_Icon_41_2.reset([]);
        this._Item_41_4._icons = this._query_Icon_41_2;
        this._query_Icon_41_2.notifyOnChanges();
      }
      if (this._query_Button_44_1.dirty) {
        this._query_Button_44_1.reset([]);
        this._Item_44_4._buttons = this._query_Button_44_1;
        this._query_Button_44_1.notifyOnChanges();
      }
      if (this._query_Icon_44_2.dirty) {
        this._query_Icon_44_2.reset([]);
        this._Item_44_4._icons = this._query_Icon_44_2;
        this._query_Icon_44_2.notifyOnChanges();
      }
      if (this._query_Button_47_1.dirty) {
        this._query_Button_47_1.reset([]);
        this._Item_47_4._buttons = this._query_Button_47_1;
        this._query_Button_47_1.notifyOnChanges();
      }
      if (this._query_Icon_47_2.dirty) {
        this._query_Icon_47_2.reset([]);
        this._Item_47_4._icons = this._query_Icon_47_2;
        this._query_Icon_47_2.notifyOnChanges();
      }
      if (this._query_Button_50_1.dirty) {
        this._query_Button_50_1.reset([]);
        this._Item_50_4._buttons = this._query_Button_50_1;
        this._query_Button_50_1.notifyOnChanges();
      }
      if (this._query_Icon_50_2.dirty) {
        this._query_Icon_50_2.reset([]);
        this._Item_50_4._icons = this._query_Icon_50_2;
        this._query_Icon_50_2.notifyOnChanges();
      }
      if (this._query_Button_53_1.dirty) {
        this._query_Button_53_1.reset([]);
        this._Item_53_4._buttons = this._query_Button_53_1;
        this._query_Button_53_1.notifyOnChanges();
      }
      if (this._query_Icon_53_2.dirty) {
        this._query_Icon_53_2.reset([]);
        this._Item_53_4._icons = this._query_Icon_53_2;
        this._query_Icon_53_2.notifyOnChanges();
      }
      if (this._query_Button_56_1.dirty) {
        this._query_Button_56_1.reset([]);
        this._Item_56_4._buttons = this._query_Button_56_1;
        this._query_Button_56_1.notifyOnChanges();
      }
      if (this._query_Icon_56_2.dirty) {
        this._query_Icon_56_2.reset([]);
        this._Item_56_4._icons = this._query_Icon_56_2;
        this._query_Icon_56_2.notifyOnChanges();
      }
      if (this._query_Button_59_1.dirty) {
        this._query_Button_59_1.reset([]);
        this._Item_59_4._buttons = this._query_Button_59_1;
        this._query_Button_59_1.notifyOnChanges();
      }
      if (this._query_Icon_59_2.dirty) {
        this._query_Icon_59_2.reset([]);
        this._Item_59_4._icons = this._query_Icon_59_2;
        this._query_Icon_59_2.notifyOnChanges();
      }
      if (this._query_Button_62_1.dirty) {
        this._query_Button_62_1.reset([]);
        this._Item_62_4._buttons = this._query_Button_62_1;
        this._query_Button_62_1.notifyOnChanges();
      }
      if (this._query_Icon_62_2.dirty) {
        this._query_Icon_62_2.reset([]);
        this._Item_62_4._icons = this._query_Icon_62_2;
        this._query_Icon_62_2.notifyOnChanges();
      }
      if (this._query_Button_65_1.dirty) {
        this._query_Button_65_1.reset([]);
        this._Item_65_4._buttons = this._query_Button_65_1;
        this._query_Button_65_1.notifyOnChanges();
      }
      if (this._query_Icon_65_2.dirty) {
        this._query_Icon_65_2.reset([]);
        this._Item_65_4._icons = this._query_Icon_65_2;
        this._query_Icon_65_2.notifyOnChanges();
      }
      if (this._query_Button_68_1.dirty) {
        this._query_Button_68_1.reset([]);
        this._Item_68_4._buttons = this._query_Button_68_1;
        this._query_Button_68_1.notifyOnChanges();
      }
      if (this._query_Icon_68_2.dirty) {
        this._query_Icon_68_2.reset([]);
        this._Item_68_4._icons = this._query_Icon_68_2;
        this._query_Icon_68_2.notifyOnChanges();
      }
      if (this._query_Button_71_1.dirty) {
        this._query_Button_71_1.reset([]);
        this._Item_71_4._buttons = this._query_Button_71_1;
        this._query_Button_71_1.notifyOnChanges();
      }
      if (this._query_Icon_71_2.dirty) {
        this._query_Icon_71_2.reset([]);
        this._Item_71_4._icons = this._query_Icon_71_2;
        this._query_Icon_71_2.notifyOnChanges();
      }
      if (this._query_Button_74_1.dirty) {
        this._query_Button_74_1.reset([]);
        this._Item_74_4._buttons = this._query_Button_74_1;
        this._query_Button_74_1.notifyOnChanges();
      }
      if (this._query_Icon_74_2.dirty) {
        this._query_Icon_74_2.reset([]);
        this._Item_74_4._icons = this._query_Icon_74_2;
        this._query_Icon_74_2.notifyOnChanges();
      }
      if (this._query_Button_77_1.dirty) {
        this._query_Button_77_1.reset([]);
        this._Item_77_4._buttons = this._query_Button_77_1;
        this._query_Button_77_1.notifyOnChanges();
      }
      if (this._query_Icon_77_2.dirty) {
        this._query_Icon_77_2.reset([]);
        this._Item_77_4._icons = this._query_Icon_77_2;
        this._query_Icon_77_2.notifyOnChanges();
      }
      if (this._query_Button_80_1.dirty) {
        this._query_Button_80_1.reset([]);
        this._Item_80_4._buttons = this._query_Button_80_1;
        this._query_Button_80_1.notifyOnChanges();
      }
      if (this._query_Icon_80_2.dirty) {
        this._query_Icon_80_2.reset([]);
        this._Item_80_4._icons = this._query_Icon_80_2;
        this._query_Icon_80_2.notifyOnChanges();
      }
      if (this._query_Button_83_1.dirty) {
        this._query_Button_83_1.reset([]);
        this._Item_83_4._buttons = this._query_Button_83_1;
        this._query_Button_83_1.notifyOnChanges();
      }
      if (this._query_Icon_83_2.dirty) {
        this._query_Icon_83_2.reset([]);
        this._Item_83_4._icons = this._query_Icon_83_2;
        this._query_Icon_83_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_14_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_17_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_20_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_26_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_29_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_32_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_35_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_38_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_41_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_44_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_47_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_50_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_53_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_56_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_59_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_62_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_65_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_68_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_71_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_74_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_77_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_80_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_83_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.ngOnDestroy();
  }
}
export function viewFactory_ToplistPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ToplistPage> {
  if ((renderType_ToplistPage === (null as any))) { (renderType_ToplistPage = viewUtils.createRenderComponentType('/Users/Perkka/booster/.tmp/pages/toplist/toplist.html',0,import9.ViewEncapsulation.None,styles_ToplistPage,{})); }
  return new _View_ToplistPage0(viewUtils,parentInjector,declarationEl);
}