/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './search';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from 'ionic-angular/components/list/list';
import * as import16 from 'ionic-angular/components/item/item';
import * as import17 from 'ionic-angular/components/list/list-header';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from 'ionic-angular/components/label/label';
import * as import20 from 'ionic-angular/components/toggle/toggle';
import * as import21 from 'ionic-angular/config/config';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from 'ionic-angular/navigation/view-controller';
import * as import24 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import25 from 'ionic-angular/components/app/app';
import * as import26 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/components/tabs/tabs';
import * as import31 from 'ionic-angular/gestures/gesture-controller';
import * as import32 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import33 from 'ionic-angular/util/form';
import * as import34 from '../../node_modules/ionic-angular/components/toggle/toggle.ngfactory';
import * as import35 from '@angular/forms/src/directives/control_value_accessor';
var renderType_SearchPage_Host:import0.RenderComponentType = (null as any);
class _View_SearchPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SearchPage_0_4:import3.SearchPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchPage_Host0,renderType_SearchPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SearchPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SearchPage_0_4 = new import3.SearchPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._SearchPage_0_4,[],compView_0);
    compView_0.create(this._SearchPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SearchPage) && (0 === requestNodeIndex))) { return this._SearchPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SearchPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SearchPage_Host === (null as any))) { (renderType_SearchPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_SearchPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SearchPageNgFactory:import10.ComponentFactory<import3.SearchPage> = new import10.ComponentFactory<import3.SearchPage>('ng-component',viewFactory_SearchPage_Host0,import3.SearchPage);
const styles_SearchPage:any[] = [];
var renderType_SearchPage:import0.RenderComponentType = (null as any);
class _View_SearchPage0 extends import1.AppView<import3.SearchPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import12.Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _ToolbarTitle_5_4:import13.ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _Content_10_4:import14.Content;
  _text_11:any;
  _el_12:any;
  _List_12_3:import15.List;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Item_14_4:import16.Item;
  _ListHeader_14_5:import17.ListHeader;
  _query_Label_14_0:import18.QueryList<any>;
  _query_Button_14_1:import18.QueryList<any>;
  _query_Icon_14_2:import18.QueryList<any>;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Item_17_4:import16.Item;
  _ItemContent_17_5:import16.ItemContent;
  _query_Label_17_0:import18.QueryList<any>;
  _query_Button_17_1:import18.QueryList<any>;
  _query_Icon_17_2:import18.QueryList<any>;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _Label_21_3:import19.Label;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _Toggle_24_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_24_5:any[];
  _text_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _Item_27_4:import16.Item;
  _ItemContent_27_5:import16.ItemContent;
  _query_Label_27_0:import18.QueryList<any>;
  _query_Button_27_1:import18.QueryList<any>;
  _query_Icon_27_2:import18.QueryList<any>;
  _text_28:any;
  _el_29:any;
  _Label_29_3:import19.Label;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _Toggle_32_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_32_5:any[];
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _Item_35_4:import16.Item;
  _ItemContent_35_5:import16.ItemContent;
  _query_Label_35_0:import18.QueryList<any>;
  _query_Button_35_1:import18.QueryList<any>;
  _query_Icon_35_2:import18.QueryList<any>;
  _text_36:any;
  _el_37:any;
  _Label_37_3:import19.Label;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import2.AppElement;
  _Toggle_40_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_40_5:any[];
  _text_41:any;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import2.AppElement;
  _Item_43_4:import16.Item;
  _ItemContent_43_5:import16.ItemContent;
  _query_Label_43_0:import18.QueryList<any>;
  _query_Button_43_1:import18.QueryList<any>;
  _query_Icon_43_2:import18.QueryList<any>;
  _text_44:any;
  _el_45:any;
  _Label_45_3:import19.Label;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  /*private*/ _appEl_48:import2.AppElement;
  _Toggle_48_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_48_5:any[];
  _text_49:any;
  _text_50:any;
  _el_51:any;
  /*private*/ _appEl_51:import2.AppElement;
  _Item_51_4:import16.Item;
  _ItemContent_51_5:import16.ItemContent;
  _query_Label_51_0:import18.QueryList<any>;
  _query_Button_51_1:import18.QueryList<any>;
  _query_Icon_51_2:import18.QueryList<any>;
  _text_52:any;
  _el_53:any;
  _Label_53_3:import19.Label;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  /*private*/ _appEl_56:import2.AppElement;
  _Toggle_56_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_56_5:any[];
  _text_57:any;
  _text_58:any;
  _el_59:any;
  /*private*/ _appEl_59:import2.AppElement;
  _Item_59_4:import16.Item;
  _ItemContent_59_5:import16.ItemContent;
  _query_Label_59_0:import18.QueryList<any>;
  _query_Button_59_1:import18.QueryList<any>;
  _query_Icon_59_2:import18.QueryList<any>;
  _text_60:any;
  _el_61:any;
  _Label_61_3:import19.Label;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  /*private*/ _appEl_64:import2.AppElement;
  _Toggle_64_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_64_5:any[];
  _text_65:any;
  _text_66:any;
  _el_67:any;
  /*private*/ _appEl_67:import2.AppElement;
  _Item_67_4:import16.Item;
  _ItemContent_67_5:import16.ItemContent;
  _query_Label_67_0:import18.QueryList<any>;
  _query_Button_67_1:import18.QueryList<any>;
  _query_Icon_67_2:import18.QueryList<any>;
  _text_68:any;
  _el_69:any;
  _Label_69_3:import19.Label;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  /*private*/ _appEl_72:import2.AppElement;
  _Toggle_72_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_72_5:any[];
  _text_73:any;
  _text_74:any;
  _el_75:any;
  /*private*/ _appEl_75:import2.AppElement;
  _Item_75_4:import16.Item;
  _ItemContent_75_5:import16.ItemContent;
  _query_Label_75_0:import18.QueryList<any>;
  _query_Button_75_1:import18.QueryList<any>;
  _query_Icon_75_2:import18.QueryList<any>;
  _text_76:any;
  _el_77:any;
  _Label_77_3:import19.Label;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  /*private*/ _appEl_80:import2.AppElement;
  _Toggle_80_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_80_5:any[];
  _text_81:any;
  _text_82:any;
  _el_83:any;
  /*private*/ _appEl_83:import2.AppElement;
  _Item_83_4:import16.Item;
  _ItemContent_83_5:import16.ItemContent;
  _query_Label_83_0:import18.QueryList<any>;
  _query_Button_83_1:import18.QueryList<any>;
  _query_Icon_83_2:import18.QueryList<any>;
  _text_84:any;
  _el_85:any;
  _Label_85_3:import19.Label;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  /*private*/ _appEl_88:import2.AppElement;
  _Toggle_88_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_88_5:any[];
  _text_89:any;
  _text_90:any;
  _el_91:any;
  /*private*/ _appEl_91:import2.AppElement;
  _Item_91_4:import16.Item;
  _ItemContent_91_5:import16.ItemContent;
  _query_Label_91_0:import18.QueryList<any>;
  _query_Button_91_1:import18.QueryList<any>;
  _query_Icon_91_2:import18.QueryList<any>;
  _text_92:any;
  _el_93:any;
  _Label_93_3:import19.Label;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  /*private*/ _appEl_96:import2.AppElement;
  _Toggle_96_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_96_5:any[];
  _text_97:any;
  _text_98:any;
  _el_99:any;
  /*private*/ _appEl_99:import2.AppElement;
  _Item_99_4:import16.Item;
  _ItemContent_99_5:import16.ItemContent;
  _query_Label_99_0:import18.QueryList<any>;
  _query_Button_99_1:import18.QueryList<any>;
  _query_Icon_99_2:import18.QueryList<any>;
  _text_100:any;
  _el_101:any;
  _Label_101_3:import19.Label;
  _text_102:any;
  _text_103:any;
  _el_104:any;
  /*private*/ _appEl_104:import2.AppElement;
  _Toggle_104_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_104_5:any[];
  _text_105:any;
  _text_106:any;
  _el_107:any;
  /*private*/ _appEl_107:import2.AppElement;
  _Item_107_4:import16.Item;
  _ItemContent_107_5:import16.ItemContent;
  _query_Label_107_0:import18.QueryList<any>;
  _query_Button_107_1:import18.QueryList<any>;
  _query_Icon_107_2:import18.QueryList<any>;
  _text_108:any;
  _el_109:any;
  _Label_109_3:import19.Label;
  _text_110:any;
  _text_111:any;
  _el_112:any;
  /*private*/ _appEl_112:import2.AppElement;
  _Toggle_112_4:import20.Toggle;
  __NG_VALUE_ACCESSOR_112_5:any[];
  _text_113:any;
  _text_114:any;
  _text_115:any;
  _text_116:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchPage0,renderType_SearchPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_24_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_24_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_24_5 = [this._Toggle_24_4]); }
    return this.__NG_VALUE_ACCESSOR_24_5;
  }
  get _NG_VALUE_ACCESSOR_32_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_32_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_32_5 = [this._Toggle_32_4]); }
    return this.__NG_VALUE_ACCESSOR_32_5;
  }
  get _NG_VALUE_ACCESSOR_40_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_40_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_40_5 = [this._Toggle_40_4]); }
    return this.__NG_VALUE_ACCESSOR_40_5;
  }
  get _NG_VALUE_ACCESSOR_48_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_48_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_48_5 = [this._Toggle_48_4]); }
    return this.__NG_VALUE_ACCESSOR_48_5;
  }
  get _NG_VALUE_ACCESSOR_56_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_56_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_56_5 = [this._Toggle_56_4]); }
    return this.__NG_VALUE_ACCESSOR_56_5;
  }
  get _NG_VALUE_ACCESSOR_64_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_64_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_64_5 = [this._Toggle_64_4]); }
    return this.__NG_VALUE_ACCESSOR_64_5;
  }
  get _NG_VALUE_ACCESSOR_72_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_72_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_72_5 = [this._Toggle_72_4]); }
    return this.__NG_VALUE_ACCESSOR_72_5;
  }
  get _NG_VALUE_ACCESSOR_80_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_80_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_80_5 = [this._Toggle_80_4]); }
    return this.__NG_VALUE_ACCESSOR_80_5;
  }
  get _NG_VALUE_ACCESSOR_88_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_88_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_88_5 = [this._Toggle_88_4]); }
    return this.__NG_VALUE_ACCESSOR_88_5;
  }
  get _NG_VALUE_ACCESSOR_96_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_96_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_96_5 = [this._Toggle_96_4]); }
    return this.__NG_VALUE_ACCESSOR_96_5;
  }
  get _NG_VALUE_ACCESSOR_104_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_104_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_104_5 = [this._Toggle_104_4]); }
    return this.__NG_VALUE_ACCESSOR_104_5;
  }
  get _NG_VALUE_ACCESSOR_112_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_112_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_112_5 = [this._Toggle_112_4]); }
    return this.__NG_VALUE_ACCESSOR_112_5;
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Header(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import23.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import24.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Navbar(this.parentInjector.get(import25.App),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,[],compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import2.AppElement(5,3,this,this._el_5);
    var compView_5:any = import26.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import13.ToolbarTitle(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_3_4);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'Search',(null as any));
    compView_5.create(this._ToolbarTitle_5_4,[[].concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4,[
      [],
      [],
      [],
      [].concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','search');
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import2.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import27.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import14.Content(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import25.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import30.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4,[],compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_12_3 = new import15.List(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import31.GestureController));
    this._text_13 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','item');
    this._appEl_14 = new import2.AppElement(14,12,this,this._el_14);
    var compView_14:any = import32.viewFactory_Item0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Item_14_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_14),this.renderer);
    this._ListHeader_14_5 = new import17.ListHeader(this.parentInjector.get(import21.Config),this.renderer,new import22.ElementRef(this._el_14),(null as any));
    this._query_Label_14_0 = new import18.QueryList<any>();
    this._query_Button_14_1 = new import18.QueryList<any>();
    this._query_Icon_14_2 = new import18.QueryList<any>();
    this._appEl_14.initComponent(this._Item_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n      Characters\n    ',(null as any));
    this._query_Label_14_0.reset([]);
    this._Item_14_4.contentLabel = this._query_Label_14_0.first;
    compView_14.create(this._Item_14_4,[
      [],
      [],
      [].concat([this._text_15]),
      [],
      []
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','item item-block');
    this._appEl_17 = new import2.AppElement(17,12,this,this._el_17);
    var compView_17:any = import32.viewFactory_Item0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Item_17_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_17),this.renderer);
    this._ItemContent_17_5 = new import16.ItemContent();
    this._query_Label_17_0 = new import18.QueryList<any>();
    this._query_Button_17_1 = new import18.QueryList<any>();
    this._query_Icon_17_2 = new import18.QueryList<any>();
    this._appEl_17.initComponent(this._Item_17_4,[],compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n       ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_19,'src','img/run.jpg');
    this._text_20 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_21_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_21),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Frodo Baggins',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_24,'checked','true');
    this.renderer.setElementAttribute(this._el_24,'value','danger');
    this._appEl_24 = new import2.AppElement(24,17,this,this._el_24);
    var compView_24:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Toggle_24_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_24),this.renderer,this._Item_17_4);
    this._appEl_24.initComponent(this._Toggle_24_4,[],compView_24);
    compView_24.create(this._Toggle_24_4,[],(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_17_0.reset([this._Label_21_3]);
    this._Item_17_4.contentLabel = this._query_Label_17_0.first;
    compView_17.create(this._Item_17_4,[
      [],
      [].concat([this._el_21]),
      [].concat([
        this._text_18,
        this._el_19,
        this._text_20,
        this._text_23,
        this._text_25
      ]
      ),
      [],
      [].concat([this._el_24])
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','item item-block');
    this._appEl_27 = new import2.AppElement(27,12,this,this._el_27);
    var compView_27:any = import32.viewFactory_Item0(this.viewUtils,this.injector(27),this._appEl_27);
    this._Item_27_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_27),this.renderer);
    this._ItemContent_27_5 = new import16.ItemContent();
    this._query_Label_27_0 = new import18.QueryList<any>();
    this._query_Button_27_1 = new import18.QueryList<any>();
    this._query_Icon_27_2 = new import18.QueryList<any>();
    this._appEl_27.initComponent(this._Item_27_4,[],compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_29_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_29),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Sam',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_32,'color','danger');
    this._appEl_32 = new import2.AppElement(32,27,this,this._el_32);
    var compView_32:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Toggle_32_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_32),this.renderer,this._Item_27_4);
    this._appEl_32.initComponent(this._Toggle_32_4,[],compView_32);
    compView_32.create(this._Toggle_32_4,[],(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_27_0.reset([this._Label_29_3]);
    this._Item_27_4.contentLabel = this._query_Label_27_0.first;
    compView_27.create(this._Item_27_4,[
      [],
      [].concat([this._el_29]),
      [].concat([
        this._text_28,
        this._text_31,
        this._text_33
      ]
      ),
      [],
      [].concat([this._el_32])
    ]
    ,(null as any));
    this._text_34 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','item item-block');
    this._appEl_35 = new import2.AppElement(35,12,this,this._el_35);
    var compView_35:any = import32.viewFactory_Item0(this.viewUtils,this.injector(35),this._appEl_35);
    this._Item_35_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_35),this.renderer);
    this._ItemContent_35_5 = new import16.ItemContent();
    this._query_Label_35_0 = new import18.QueryList<any>();
    this._query_Button_35_1 = new import18.QueryList<any>();
    this._query_Icon_35_2 = new import18.QueryList<any>();
    this._appEl_35.initComponent(this._Item_35_4,[],compView_35);
    this._text_36 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_37_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_37),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Éowyn',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_40,'checked','true');
    this.renderer.setElementAttribute(this._el_40,'color','danger');
    this._appEl_40 = new import2.AppElement(40,35,this,this._el_40);
    var compView_40:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(40),this._appEl_40);
    this._Toggle_40_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_40),this.renderer,this._Item_35_4);
    this._appEl_40.initComponent(this._Toggle_40_4,[],compView_40);
    compView_40.create(this._Toggle_40_4,[],(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_35_0.reset([this._Label_37_3]);
    this._Item_35_4.contentLabel = this._query_Label_35_0.first;
    compView_35.create(this._Item_35_4,[
      [],
      [].concat([this._el_37]),
      [].concat([
        this._text_36,
        this._text_39,
        this._text_41
      ]
      ),
      [],
      [].concat([this._el_40])
    ]
    ,(null as any));
    this._text_42 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','item item-block');
    this._appEl_43 = new import2.AppElement(43,12,this,this._el_43);
    var compView_43:any = import32.viewFactory_Item0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Item_43_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_43),this.renderer);
    this._ItemContent_43_5 = new import16.ItemContent();
    this._query_Label_43_0 = new import18.QueryList<any>();
    this._query_Button_43_1 = new import18.QueryList<any>();
    this._query_Icon_43_2 = new import18.QueryList<any>();
    this._appEl_43.initComponent(this._Item_43_4,[],compView_43);
    this._text_44 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_45_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_45),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'Legolas',(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_48 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_48,'checked','true');
    this.renderer.setElementAttribute(this._el_48,'color','danger');
    this._appEl_48 = new import2.AppElement(48,43,this,this._el_48);
    var compView_48:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(48),this._appEl_48);
    this._Toggle_48_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_48),this.renderer,this._Item_43_4);
    this._appEl_48.initComponent(this._Toggle_48_4,[],compView_48);
    compView_48.create(this._Toggle_48_4,[],(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_43_0.reset([this._Label_45_3]);
    this._Item_43_4.contentLabel = this._query_Label_43_0.first;
    compView_43.create(this._Item_43_4,[
      [],
      [].concat([this._el_45]),
      [].concat([
        this._text_44,
        this._text_47,
        this._text_49
      ]
      ),
      [],
      [].concat([this._el_48])
    ]
    ,(null as any));
    this._text_50 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','item item-block');
    this._appEl_51 = new import2.AppElement(51,12,this,this._el_51);
    var compView_51:any = import32.viewFactory_Item0(this.viewUtils,this.injector(51),this._appEl_51);
    this._Item_51_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_51),this.renderer);
    this._ItemContent_51_5 = new import16.ItemContent();
    this._query_Label_51_0 = new import18.QueryList<any>();
    this._query_Button_51_1 = new import18.QueryList<any>();
    this._query_Icon_51_2 = new import18.QueryList<any>();
    this._appEl_51.initComponent(this._Item_51_4,[],compView_51);
    this._text_52 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_53_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_53),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'Gimli',(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_56,'color','danger');
    this._appEl_56 = new import2.AppElement(56,51,this,this._el_56);
    var compView_56:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(56),this._appEl_56);
    this._Toggle_56_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_56),this.renderer,this._Item_51_4);
    this._appEl_56.initComponent(this._Toggle_56_4,[],compView_56);
    compView_56.create(this._Toggle_56_4,[],(null as any));
    this._text_57 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_51_0.reset([this._Label_53_3]);
    this._Item_51_4.contentLabel = this._query_Label_51_0.first;
    compView_51.create(this._Item_51_4,[
      [],
      [].concat([this._el_53]),
      [].concat([
        this._text_52,
        this._text_55,
        this._text_57
      ]
      ),
      [],
      [].concat([this._el_56])
    ]
    ,(null as any));
    this._text_58 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','item item-block');
    this._appEl_59 = new import2.AppElement(59,12,this,this._el_59);
    var compView_59:any = import32.viewFactory_Item0(this.viewUtils,this.injector(59),this._appEl_59);
    this._Item_59_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_59),this.renderer);
    this._ItemContent_59_5 = new import16.ItemContent();
    this._query_Label_59_0 = new import18.QueryList<any>();
    this._query_Button_59_1 = new import18.QueryList<any>();
    this._query_Icon_59_2 = new import18.QueryList<any>();
    this._appEl_59.initComponent(this._Item_59_4,[],compView_59);
    this._text_60 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_61 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_61_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_61),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'Saruman',(null as any));
    this._text_63 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_64 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_64,'checked','true');
    this.renderer.setElementAttribute(this._el_64,'color','danger');
    this._appEl_64 = new import2.AppElement(64,59,this,this._el_64);
    var compView_64:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(64),this._appEl_64);
    this._Toggle_64_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_64),this.renderer,this._Item_59_4);
    this._appEl_64.initComponent(this._Toggle_64_4,[],compView_64);
    compView_64.create(this._Toggle_64_4,[],(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_59_0.reset([this._Label_61_3]);
    this._Item_59_4.contentLabel = this._query_Label_59_0.first;
    compView_59.create(this._Item_59_4,[
      [],
      [].concat([this._el_61]),
      [].concat([
        this._text_60,
        this._text_63,
        this._text_65
      ]
      ),
      [],
      [].concat([this._el_64])
    ]
    ,(null as any));
    this._text_66 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','item item-block');
    this._appEl_67 = new import2.AppElement(67,12,this,this._el_67);
    var compView_67:any = import32.viewFactory_Item0(this.viewUtils,this.injector(67),this._appEl_67);
    this._Item_67_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_67),this.renderer);
    this._ItemContent_67_5 = new import16.ItemContent();
    this._query_Label_67_0 = new import18.QueryList<any>();
    this._query_Button_67_1 = new import18.QueryList<any>();
    this._query_Icon_67_2 = new import18.QueryList<any>();
    this._appEl_67.initComponent(this._Item_67_4,[],compView_67);
    this._text_68 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_69 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_69_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_69),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'Gandalf',(null as any));
    this._text_71 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_72 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_72,'checked','true');
    this.renderer.setElementAttribute(this._el_72,'color','danger');
    this._appEl_72 = new import2.AppElement(72,67,this,this._el_72);
    var compView_72:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(72),this._appEl_72);
    this._Toggle_72_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_72),this.renderer,this._Item_67_4);
    this._appEl_72.initComponent(this._Toggle_72_4,[],compView_72);
    compView_72.create(this._Toggle_72_4,[],(null as any));
    this._text_73 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_67_0.reset([this._Label_69_3]);
    this._Item_67_4.contentLabel = this._query_Label_67_0.first;
    compView_67.create(this._Item_67_4,[
      [],
      [].concat([this._el_69]),
      [].concat([
        this._text_68,
        this._text_71,
        this._text_73
      ]
      ),
      [],
      [].concat([this._el_72])
    ]
    ,(null as any));
    this._text_74 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_75,'class','item item-block');
    this._appEl_75 = new import2.AppElement(75,12,this,this._el_75);
    var compView_75:any = import32.viewFactory_Item0(this.viewUtils,this.injector(75),this._appEl_75);
    this._Item_75_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_75),this.renderer);
    this._ItemContent_75_5 = new import16.ItemContent();
    this._query_Label_75_0 = new import18.QueryList<any>();
    this._query_Button_75_1 = new import18.QueryList<any>();
    this._query_Icon_75_2 = new import18.QueryList<any>();
    this._appEl_75.initComponent(this._Item_75_4,[],compView_75);
    this._text_76 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_77 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_77_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_77),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'Arwen',(null as any));
    this._text_79 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_80 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_80,'color','danger');
    this._appEl_80 = new import2.AppElement(80,75,this,this._el_80);
    var compView_80:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(80),this._appEl_80);
    this._Toggle_80_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_80),this.renderer,this._Item_75_4);
    this._appEl_80.initComponent(this._Toggle_80_4,[],compView_80);
    compView_80.create(this._Toggle_80_4,[],(null as any));
    this._text_81 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_75_0.reset([this._Label_77_3]);
    this._Item_75_4.contentLabel = this._query_Label_75_0.first;
    compView_75.create(this._Item_75_4,[
      [],
      [].concat([this._el_77]),
      [].concat([
        this._text_76,
        this._text_79,
        this._text_81
      ]
      ),
      [],
      [].concat([this._el_80])
    ]
    ,(null as any));
    this._text_82 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_83 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_83,'class','item item-block');
    this._appEl_83 = new import2.AppElement(83,12,this,this._el_83);
    var compView_83:any = import32.viewFactory_Item0(this.viewUtils,this.injector(83),this._appEl_83);
    this._Item_83_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_83),this.renderer);
    this._ItemContent_83_5 = new import16.ItemContent();
    this._query_Label_83_0 = new import18.QueryList<any>();
    this._query_Button_83_1 = new import18.QueryList<any>();
    this._query_Icon_83_2 = new import18.QueryList<any>();
    this._appEl_83.initComponent(this._Item_83_4,[],compView_83);
    this._text_84 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_85 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_85_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_85),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'Treebeard',(null as any));
    this._text_87 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_88 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_88,'checked','true');
    this.renderer.setElementAttribute(this._el_88,'color','danger');
    this._appEl_88 = new import2.AppElement(88,83,this,this._el_88);
    var compView_88:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(88),this._appEl_88);
    this._Toggle_88_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_88),this.renderer,this._Item_83_4);
    this._appEl_88.initComponent(this._Toggle_88_4,[],compView_88);
    compView_88.create(this._Toggle_88_4,[],(null as any));
    this._text_89 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_83_0.reset([this._Label_85_3]);
    this._Item_83_4.contentLabel = this._query_Label_83_0.first;
    compView_83.create(this._Item_83_4,[
      [],
      [].concat([this._el_85]),
      [].concat([
        this._text_84,
        this._text_87,
        this._text_89
      ]
      ),
      [],
      [].concat([this._el_88])
    ]
    ,(null as any));
    this._text_90 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_91 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_91,'class','item item-block');
    this._appEl_91 = new import2.AppElement(91,12,this,this._el_91);
    var compView_91:any = import32.viewFactory_Item0(this.viewUtils,this.injector(91),this._appEl_91);
    this._Item_91_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_91),this.renderer);
    this._ItemContent_91_5 = new import16.ItemContent();
    this._query_Label_91_0 = new import18.QueryList<any>();
    this._query_Button_91_1 = new import18.QueryList<any>();
    this._query_Icon_91_2 = new import18.QueryList<any>();
    this._appEl_91.initComponent(this._Item_91_4,[],compView_91);
    this._text_92 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_93 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_93_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_93),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_94 = this.renderer.createText(this._el_93,'Boromir',(null as any));
    this._text_95 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_96 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_96,'color','danger');
    this._appEl_96 = new import2.AppElement(96,91,this,this._el_96);
    var compView_96:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(96),this._appEl_96);
    this._Toggle_96_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_96),this.renderer,this._Item_91_4);
    this._appEl_96.initComponent(this._Toggle_96_4,[],compView_96);
    compView_96.create(this._Toggle_96_4,[],(null as any));
    this._text_97 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_91_0.reset([this._Label_93_3]);
    this._Item_91_4.contentLabel = this._query_Label_91_0.first;
    compView_91.create(this._Item_91_4,[
      [],
      [].concat([this._el_93]),
      [].concat([
        this._text_92,
        this._text_95,
        this._text_97
      ]
      ),
      [],
      [].concat([this._el_96])
    ]
    ,(null as any));
    this._text_98 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_99 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_99,'class','item item-block');
    this._appEl_99 = new import2.AppElement(99,12,this,this._el_99);
    var compView_99:any = import32.viewFactory_Item0(this.viewUtils,this.injector(99),this._appEl_99);
    this._Item_99_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_99),this.renderer);
    this._ItemContent_99_5 = new import16.ItemContent();
    this._query_Label_99_0 = new import18.QueryList<any>();
    this._query_Button_99_1 = new import18.QueryList<any>();
    this._query_Icon_99_2 = new import18.QueryList<any>();
    this._appEl_99.initComponent(this._Item_99_4,[],compView_99);
    this._text_100 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_101 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_101_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_101),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'Gollum',(null as any));
    this._text_103 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_104 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_104,'checked','true');
    this.renderer.setElementAttribute(this._el_104,'color','danger');
    this._appEl_104 = new import2.AppElement(104,99,this,this._el_104);
    var compView_104:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(104),this._appEl_104);
    this._Toggle_104_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_104),this.renderer,this._Item_99_4);
    this._appEl_104.initComponent(this._Toggle_104_4,[],compView_104);
    compView_104.create(this._Toggle_104_4,[],(null as any));
    this._text_105 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_99_0.reset([this._Label_101_3]);
    this._Item_99_4.contentLabel = this._query_Label_99_0.first;
    compView_99.create(this._Item_99_4,[
      [],
      [].concat([this._el_101]),
      [].concat([
        this._text_100,
        this._text_103,
        this._text_105
      ]
      ),
      [],
      [].concat([this._el_104])
    ]
    ,(null as any));
    this._text_106 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_107 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_107,'class','item item-block');
    this._appEl_107 = new import2.AppElement(107,12,this,this._el_107);
    var compView_107:any = import32.viewFactory_Item0(this.viewUtils,this.injector(107),this._appEl_107);
    this._Item_107_4 = new import16.Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_107),this.renderer);
    this._ItemContent_107_5 = new import16.ItemContent();
    this._query_Label_107_0 = new import18.QueryList<any>();
    this._query_Button_107_1 = new import18.QueryList<any>();
    this._query_Icon_107_2 = new import18.QueryList<any>();
    this._appEl_107.initComponent(this._Item_107_4,[],compView_107);
    this._text_108 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_109 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_109_3 = new import19.Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_109),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_110 = this.renderer.createText(this._el_109,'Galadriel',(null as any));
    this._text_111 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_112 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_112,'color','danger');
    this._appEl_112 = new import2.AppElement(112,107,this,this._el_112);
    var compView_112:any = import34.viewFactory_Toggle0(this.viewUtils,this.injector(112),this._appEl_112);
    this._Toggle_112_4 = new import20.Toggle(this.parentInjector.get(import33.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_112),this.renderer,this._Item_107_4);
    this._appEl_112.initComponent(this._Toggle_112_4,[],compView_112);
    compView_112.create(this._Toggle_112_4,[],(null as any));
    this._text_113 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_107_0.reset([this._Label_109_3]);
    this._Item_107_4.contentLabel = this._query_Label_107_0.first;
    compView_107.create(this._Item_107_4,[
      [],
      [].concat([this._el_109]),
      [].concat([
        this._text_108,
        this._text_111,
        this._text_113
      ]
      ),
      [],
      [].concat([this._el_112])
    ]
    ,(null as any));
    this._text_114 = this.renderer.createText(this._el_12,'\n\n\n  ',(null as any));
    this._text_115 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    compView_10.create(this._Content_10_4,[
      [],
      [].concat([
        this._text_11,
        this._el_12,
        this._text_115
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_116 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._text_114,
      this._text_115,
      this._text_116
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4; }
    if (((token === import12.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4; }
    if (((token === import11.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3; }
    if (((token === import16.Item) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Item_14_4; }
    if (((token === import17.ListHeader) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ListHeader_14_5; }
    if (((token === import19.Label) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Label_21_3; }
    if (((token === import20.Toggle) && (24 === requestNodeIndex))) { return this._Toggle_24_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (24 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_24_5; }
    if (((token === import16.Item) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Item_17_4; }
    if (((token === import16.ItemContent) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._ItemContent_17_5; }
    if (((token === import19.Label) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Label_29_3; }
    if (((token === import20.Toggle) && (32 === requestNodeIndex))) { return this._Toggle_32_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (32 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_32_5; }
    if (((token === import16.Item) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Item_27_4; }
    if (((token === import16.ItemContent) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._ItemContent_27_5; }
    if (((token === import19.Label) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Label_37_3; }
    if (((token === import20.Toggle) && (40 === requestNodeIndex))) { return this._Toggle_40_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (40 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_40_5; }
    if (((token === import16.Item) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Item_35_4; }
    if (((token === import16.ItemContent) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ItemContent_35_5; }
    if (((token === import19.Label) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Label_45_3; }
    if (((token === import20.Toggle) && (48 === requestNodeIndex))) { return this._Toggle_48_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (48 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_48_5; }
    if (((token === import16.Item) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Item_43_4; }
    if (((token === import16.ItemContent) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._ItemContent_43_5; }
    if (((token === import19.Label) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Label_53_3; }
    if (((token === import20.Toggle) && (56 === requestNodeIndex))) { return this._Toggle_56_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (56 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_56_5; }
    if (((token === import16.Item) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Item_51_4; }
    if (((token === import16.ItemContent) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._ItemContent_51_5; }
    if (((token === import19.Label) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 62)))) { return this._Label_61_3; }
    if (((token === import20.Toggle) && (64 === requestNodeIndex))) { return this._Toggle_64_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (64 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_64_5; }
    if (((token === import16.Item) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Item_59_4; }
    if (((token === import16.ItemContent) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._ItemContent_59_5; }
    if (((token === import19.Label) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._Label_69_3; }
    if (((token === import20.Toggle) && (72 === requestNodeIndex))) { return this._Toggle_72_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (72 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_72_5; }
    if (((token === import16.Item) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Item_67_4; }
    if (((token === import16.ItemContent) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._ItemContent_67_5; }
    if (((token === import19.Label) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._Label_77_3; }
    if (((token === import20.Toggle) && (80 === requestNodeIndex))) { return this._Toggle_80_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (80 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_80_5; }
    if (((token === import16.Item) && ((75 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._Item_75_4; }
    if (((token === import16.ItemContent) && ((75 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._ItemContent_75_5; }
    if (((token === import19.Label) && ((85 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._Label_85_3; }
    if (((token === import20.Toggle) && (88 === requestNodeIndex))) { return this._Toggle_88_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (88 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_88_5; }
    if (((token === import16.Item) && ((83 <= requestNodeIndex) && (requestNodeIndex <= 89)))) { return this._Item_83_4; }
    if (((token === import16.ItemContent) && ((83 <= requestNodeIndex) && (requestNodeIndex <= 89)))) { return this._ItemContent_83_5; }
    if (((token === import19.Label) && ((93 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._Label_93_3; }
    if (((token === import20.Toggle) && (96 === requestNodeIndex))) { return this._Toggle_96_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (96 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_96_5; }
    if (((token === import16.Item) && ((91 <= requestNodeIndex) && (requestNodeIndex <= 97)))) { return this._Item_91_4; }
    if (((token === import16.ItemContent) && ((91 <= requestNodeIndex) && (requestNodeIndex <= 97)))) { return this._ItemContent_91_5; }
    if (((token === import19.Label) && ((101 <= requestNodeIndex) && (requestNodeIndex <= 102)))) { return this._Label_101_3; }
    if (((token === import20.Toggle) && (104 === requestNodeIndex))) { return this._Toggle_104_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (104 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_104_5; }
    if (((token === import16.Item) && ((99 <= requestNodeIndex) && (requestNodeIndex <= 105)))) { return this._Item_99_4; }
    if (((token === import16.ItemContent) && ((99 <= requestNodeIndex) && (requestNodeIndex <= 105)))) { return this._ItemContent_99_5; }
    if (((token === import19.Label) && ((109 <= requestNodeIndex) && (requestNodeIndex <= 110)))) { return this._Label_109_3; }
    if (((token === import20.Toggle) && (112 === requestNodeIndex))) { return this._Toggle_112_4; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (112 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_112_5; }
    if (((token === import16.Item) && ((107 <= requestNodeIndex) && (requestNodeIndex <= 113)))) { return this._Item_107_4; }
    if (((token === import16.ItemContent) && ((107 <= requestNodeIndex) && (requestNodeIndex <= 113)))) { return this._ItemContent_107_5; }
    if (((token === import15.List) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 114)))) { return this._List_12_3; }
    if (((token === import14.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 115)))) { return this._Content_10_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_10_4.ngOnInit(); }
    const currVal_3:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Toggle_24_4.checked = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Toggle_32_4.color = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Toggle_40_4.color = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Toggle_40_4.checked = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_10:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Toggle_48_4.color = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Toggle_48_4.checked = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_13:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Toggle_56_4.color = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Toggle_64_4.color = currVal_15;
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Toggle_64_4.checked = currVal_16;
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._Toggle_72_4.color = currVal_18;
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._Toggle_72_4.checked = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_21:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._Toggle_80_4.color = currVal_21;
      this._expr_21 = currVal_21;
    }
    const currVal_23:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._Toggle_88_4.color = currVal_23;
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._Toggle_88_4.checked = currVal_24;
      this._expr_24 = currVal_24;
    }
    const currVal_26:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._Toggle_96_4.color = currVal_26;
      this._expr_26 = currVal_26;
    }
    const currVal_28:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._Toggle_104_4.color = currVal_28;
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._Toggle_104_4.checked = currVal_29;
      this._expr_29 = currVal_29;
    }
    const currVal_31:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._Toggle_112_4.color = currVal_31;
      this._expr_31 = currVal_31;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_14_1.dirty) {
        this._query_Button_14_1.reset([]);
        this._Item_14_4._buttons = this._query_Button_14_1;
        this._query_Button_14_1.notifyOnChanges();
      }
      if (this._query_Icon_14_2.dirty) {
        this._query_Icon_14_2.reset([]);
        this._Item_14_4._icons = this._query_Icon_14_2;
        this._query_Icon_14_2.notifyOnChanges();
      }
      if (this._query_Button_17_1.dirty) {
        this._query_Button_17_1.reset([]);
        this._Item_17_4._buttons = this._query_Button_17_1;
        this._query_Button_17_1.notifyOnChanges();
      }
      if (this._query_Icon_17_2.dirty) {
        this._query_Icon_17_2.reset([]);
        this._Item_17_4._icons = this._query_Icon_17_2;
        this._query_Icon_17_2.notifyOnChanges();
      }
      if (this._query_Button_27_1.dirty) {
        this._query_Button_27_1.reset([]);
        this._Item_27_4._buttons = this._query_Button_27_1;
        this._query_Button_27_1.notifyOnChanges();
      }
      if (this._query_Icon_27_2.dirty) {
        this._query_Icon_27_2.reset([]);
        this._Item_27_4._icons = this._query_Icon_27_2;
        this._query_Icon_27_2.notifyOnChanges();
      }
      if (this._query_Button_35_1.dirty) {
        this._query_Button_35_1.reset([]);
        this._Item_35_4._buttons = this._query_Button_35_1;
        this._query_Button_35_1.notifyOnChanges();
      }
      if (this._query_Icon_35_2.dirty) {
        this._query_Icon_35_2.reset([]);
        this._Item_35_4._icons = this._query_Icon_35_2;
        this._query_Icon_35_2.notifyOnChanges();
      }
      if (this._query_Button_43_1.dirty) {
        this._query_Button_43_1.reset([]);
        this._Item_43_4._buttons = this._query_Button_43_1;
        this._query_Button_43_1.notifyOnChanges();
      }
      if (this._query_Icon_43_2.dirty) {
        this._query_Icon_43_2.reset([]);
        this._Item_43_4._icons = this._query_Icon_43_2;
        this._query_Icon_43_2.notifyOnChanges();
      }
      if (this._query_Button_51_1.dirty) {
        this._query_Button_51_1.reset([]);
        this._Item_51_4._buttons = this._query_Button_51_1;
        this._query_Button_51_1.notifyOnChanges();
      }
      if (this._query_Icon_51_2.dirty) {
        this._query_Icon_51_2.reset([]);
        this._Item_51_4._icons = this._query_Icon_51_2;
        this._query_Icon_51_2.notifyOnChanges();
      }
      if (this._query_Button_59_1.dirty) {
        this._query_Button_59_1.reset([]);
        this._Item_59_4._buttons = this._query_Button_59_1;
        this._query_Button_59_1.notifyOnChanges();
      }
      if (this._query_Icon_59_2.dirty) {
        this._query_Icon_59_2.reset([]);
        this._Item_59_4._icons = this._query_Icon_59_2;
        this._query_Icon_59_2.notifyOnChanges();
      }
      if (this._query_Button_67_1.dirty) {
        this._query_Button_67_1.reset([]);
        this._Item_67_4._buttons = this._query_Button_67_1;
        this._query_Button_67_1.notifyOnChanges();
      }
      if (this._query_Icon_67_2.dirty) {
        this._query_Icon_67_2.reset([]);
        this._Item_67_4._icons = this._query_Icon_67_2;
        this._query_Icon_67_2.notifyOnChanges();
      }
      if (this._query_Button_75_1.dirty) {
        this._query_Button_75_1.reset([]);
        this._Item_75_4._buttons = this._query_Button_75_1;
        this._query_Button_75_1.notifyOnChanges();
      }
      if (this._query_Icon_75_2.dirty) {
        this._query_Icon_75_2.reset([]);
        this._Item_75_4._icons = this._query_Icon_75_2;
        this._query_Icon_75_2.notifyOnChanges();
      }
      if (this._query_Button_83_1.dirty) {
        this._query_Button_83_1.reset([]);
        this._Item_83_4._buttons = this._query_Button_83_1;
        this._query_Button_83_1.notifyOnChanges();
      }
      if (this._query_Icon_83_2.dirty) {
        this._query_Icon_83_2.reset([]);
        this._Item_83_4._icons = this._query_Icon_83_2;
        this._query_Icon_83_2.notifyOnChanges();
      }
      if (this._query_Button_91_1.dirty) {
        this._query_Button_91_1.reset([]);
        this._Item_91_4._buttons = this._query_Button_91_1;
        this._query_Button_91_1.notifyOnChanges();
      }
      if (this._query_Icon_91_2.dirty) {
        this._query_Icon_91_2.reset([]);
        this._Item_91_4._icons = this._query_Icon_91_2;
        this._query_Icon_91_2.notifyOnChanges();
      }
      if (this._query_Button_99_1.dirty) {
        this._query_Button_99_1.reset([]);
        this._Item_99_4._buttons = this._query_Button_99_1;
        this._query_Button_99_1.notifyOnChanges();
      }
      if (this._query_Icon_99_2.dirty) {
        this._query_Icon_99_2.reset([]);
        this._Item_99_4._icons = this._query_Icon_99_2;
        this._query_Icon_99_2.notifyOnChanges();
      }
      if (this._query_Button_107_1.dirty) {
        this._query_Button_107_1.reset([]);
        this._Item_107_4._buttons = this._query_Button_107_1;
        this._query_Button_107_1.notifyOnChanges();
      }
      if (this._query_Icon_107_2.dirty) {
        this._query_Icon_107_2.reset([]);
        this._Item_107_4._icons = this._query_Icon_107_2;
        this._query_Icon_107_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_14_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_24_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_17_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_32_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_27_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_40_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_35_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_48_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_43_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_56_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_51_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_64_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_59_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_72_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_67_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_80_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_75_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_88_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_83_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_96_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_91_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_104_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_99_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_112_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_107_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Toggle_24_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_24,'toggle-disabled',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Toggle_32_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_32,'toggle-disabled',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = this._Toggle_40_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_40,'toggle-disabled',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_12:any = this._Toggle_48_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_48,'toggle-disabled',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this._Toggle_56_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_56,'toggle-disabled',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_17:any = this._Toggle_64_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_64,'toggle-disabled',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_20:any = this._Toggle_72_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_72,'toggle-disabled',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_22:any = this._Toggle_80_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_80,'toggle-disabled',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_25:any = this._Toggle_88_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_88,'toggle-disabled',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_27:any = this._Toggle_96_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_96,'toggle-disabled',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_30:any = this._Toggle_104_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_104,'toggle-disabled',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_32:any = this._Toggle_112_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_112,'toggle-disabled',currVal_32);
      this._expr_32 = currVal_32;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Toggle_24_4.ngOnDestroy();
    this._Toggle_32_4.ngOnDestroy();
    this._Toggle_40_4.ngOnDestroy();
    this._Toggle_48_4.ngOnDestroy();
    this._Toggle_56_4.ngOnDestroy();
    this._Toggle_64_4.ngOnDestroy();
    this._Toggle_72_4.ngOnDestroy();
    this._Toggle_80_4.ngOnDestroy();
    this._Toggle_88_4.ngOnDestroy();
    this._Toggle_96_4.ngOnDestroy();
    this._Toggle_104_4.ngOnDestroy();
    this._Toggle_112_4.ngOnDestroy();
    this._Content_10_4.ngOnDestroy();
  }
}
export function viewFactory_SearchPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SearchPage> {
  if ((renderType_SearchPage === (null as any))) { (renderType_SearchPage = viewUtils.createRenderComponentType('/Users/Perkka/booster/.tmp/pages/search/search.html',0,import9.ViewEncapsulation.None,styles_SearchPage,{})); }
  return new _View_SearchPage0(viewUtils,parentInjector,declarationEl);
}