/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './explore';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../services/request';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from 'ionic-angular/components/toolbar/toolbar';
import * as import13 from 'ionic-angular/components/navbar/navbar';
import * as import14 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import15 from 'ionic-angular/components/content/content';
import * as import16 from 'ionic-angular/components/scroll/scroll';
import * as import17 from 'ionic-angular/components/grid/grid';
import * as import18 from 'ionic-angular/components/card/card';
import * as import19 from 'ionic-angular/components/list/list';
import * as import20 from 'ionic-angular/components/item/item';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from 'ionic-angular/components/icon/icon';
import * as import23 from '@angular/common/src/directives/ng_for';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from '../../node_modules/ionic-angular/components/scroll/scroll.ngfactory';
import * as import35 from 'ionic-angular/gestures/gesture-controller';
import * as import36 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import37 from 'ionic-angular/util/form';
import * as import38 from '@angular/core/src/linker/template_ref';
import * as import39 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import40 from '@angular/common/src/directives/ng_if';
var renderType_ExplorePage_Host:import0.RenderComponentType = (null as any);
class _View_ExplorePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ExplorePage_0_4:import3.ExplorePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ExplorePage_Host0,renderType_ExplorePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ExplorePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ExplorePage_0_4 = new import3.ExplorePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.Request));
    this._appEl_0.initComponent(this._ExplorePage_0_4,[],compView_0);
    compView_0.create(this._ExplorePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ExplorePage) && (0 === requestNodeIndex))) { return this._ExplorePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ExplorePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ExplorePage_Host === (null as any))) { (renderType_ExplorePage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_ExplorePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ExplorePageNgFactory:import11.ComponentFactory<import3.ExplorePage> = new import11.ComponentFactory<import3.ExplorePage>('ng-component',viewFactory_ExplorePage_Host0,import3.ExplorePage);
const styles_ExplorePage:any[] = [];
var renderType_ExplorePage:import0.RenderComponentType = (null as any);
class _View_ExplorePage0 extends import1.AppView<import3.ExplorePage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import12.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import13.Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _ToolbarTitle_5_4:import14.ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _Content_10_4:import15.Content;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _Scroll_13_4:import16.Scroll;
  _text_14:any;
  _el_15:any;
  _Row_15_3:import17.Row;
  _text_16:any;
  _el_17:any;
  _Col_17_3:import17.Col;
  _text_18:any;
  _el_19:any;
  _Card_19_3:import18.Card;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _Col_28_3:import17.Col;
  _text_29:any;
  _el_30:any;
  _Card_30_3:import18.Card;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _Col_39_3:import17.Col;
  _text_40:any;
  _el_41:any;
  _Card_41_3:import18.Card;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _List_53_3:import19.List;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  /*private*/ _appEl_56:import2.AppElement;
  _Item_56_4:import20.Item;
  _ItemContent_56_5:import20.ItemContent;
  _query_Label_56_0:import21.QueryList<any>;
  _query_Button_56_1:import21.QueryList<any>;
  _query_Icon_56_2:import21.QueryList<any>;
  _text_57:any;
  _el_58:any;
  _Icon_58_3:import22.Icon;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  /*private*/ _appEl_62:import2.AppElement;
  _Item_62_4:import20.Item;
  _ItemContent_62_5:import20.ItemContent;
  _query_Label_62_0:import21.QueryList<any>;
  _query_Button_62_1:import21.QueryList<any>;
  _query_Icon_62_2:import21.QueryList<any>;
  _text_63:any;
  _el_64:any;
  _Icon_64_3:import22.Icon;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _Row_73_3:import17.Row;
  _text_74:any;
  _el_75:any;
  _Col_75_3:import17.Col;
  _text_76:any;
  _anchor_77:any;
  /*private*/ _appEl_77:import2.AppElement;
  _TemplateRef_77_5:any;
  _NgFor_77_6:import23.NgFor;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _Col_80_3:import17.Col;
  _text_81:any;
  _anchor_82:any;
  /*private*/ _appEl_82:import2.AppElement;
  _TemplateRef_82_5:any;
  _NgFor_82_6:import23.NgFor;
  _text_83:any;
  _text_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ExplorePage0,renderType_ExplorePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import12.Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import27.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import13.Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,[],compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import2.AppElement(5,3,this,this._el_5);
    var compView_5:any = import29.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import14.ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_3_4);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'Explore',(null as any));
    compView_5.create(this._ToolbarTitle_5_4,[[].concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4,[
      [],
      [],
      [],
      [].concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','explore');
    this._appEl_10 = new import2.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import30.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import15.Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4,[],compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-scroll',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','item');
    this.renderer.setElementAttribute(this._el_13,'id','sccc');
    this.renderer.setElementAttribute(this._el_13,'scrollX','true');
    this.renderer.setElementAttribute(this._el_13,'style','height:200px');
    this._appEl_13 = new import2.AppElement(13,10,this,this._el_13);
    var compView_13:any = import34.viewFactory_Scroll0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Scroll_13_4 = new import16.Scroll(new import25.ElementRef(this._el_13));
    this._appEl_13.initComponent(this._Scroll_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_15_3 = new import17.Row();
    this._text_16 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_17,'width-50','');
    this._Col_17_3 = new import17.Col();
    this._text_18 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'ion-card',(null as any));
    this._Card_19_3 = new import18.Card(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_19,'\n                     ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'img',(null as any));
    this.renderer.setElementAttribute(this._el_21,'src','img/health.png');
    this._text_22 = this.renderer.createText(this._el_19,'\n                      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','card-title');
    this._text_24 = this.renderer.createText(this._el_23,'hej',(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n                  ',(null as any));
    this._text_26 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._text_27 = this.renderer.createText(this._el_15,' \n            ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_15,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_28,'width-50','');
    this._Col_28_3 = new import17.Col();
    this._text_29 = this.renderer.createText(this._el_28,'\n               ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'ion-card',(null as any));
    this._Card_30_3 = new import18.Card(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_30),this.renderer);
    this._text_31 = this.renderer.createText(this._el_30,'\n                     ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'img',(null as any));
    this.renderer.setElementAttribute(this._el_32,'src','img/muscle.png');
    this._text_33 = this.renderer.createText(this._el_30,'\n                     ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_30,'div',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','card-title');
    this._text_35 = this.renderer.createText(this._el_34,'hej',(null as any));
    this._text_36 = this.renderer.createText(this._el_30,'\n                  ',(null as any));
    this._text_37 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._text_38 = this.renderer.createText(this._el_15,' \n            ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_15,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_39,'width-50','');
    this._Col_39_3 = new import17.Col();
    this._text_40 = this.renderer.createText(this._el_39,'\n               ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'ion-card',(null as any));
    this._Card_41_3 = new import18.Card(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_41),this.renderer);
    this._text_42 = this.renderer.createText(this._el_41,'\n                     ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'img',(null as any));
    this.renderer.setElementAttribute(this._el_43,'src','img/weigth.png');
    this._text_44 = this.renderer.createText(this._el_41,'\n                     ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_41,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','card-title');
    this._text_46 = this.renderer.createText(this._el_45,'hej',(null as any));
    this._text_47 = this.renderer.createText(this._el_41,'\n                  ',(null as any));
    this._text_48 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._text_49 = this.renderer.createText(this._el_15,' \n        ',(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_13.create(this._Scroll_13_4,[[].concat([
        this._text_14,
        this._el_15,
        this._text_50
      ]
    )],(null as any));
    this._text_51 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_53,'no-lines','');
    this._List_53_3 = new import19.List(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_53),this.renderer,this.parentInjector.get(import35.GestureController));
    this._text_54 = this.renderer.createText(this._el_53,'\n\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_53,'\n  ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_53,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','item item-block');
    this._appEl_56 = new import2.AppElement(56,53,this,this._el_56);
    var compView_56:any = import36.viewFactory_Item0(this.viewUtils,this.injector(56),this._appEl_56);
    this._Item_56_4 = new import20.Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_56),this.renderer);
    this._ItemContent_56_5 = new import20.ItemContent();
    this._query_Label_56_0 = new import21.QueryList<any>();
    this._query_Button_56_1 = new import21.QueryList<any>();
    this._query_Icon_56_2 = new import21.QueryList<any>();
    this._appEl_56.initComponent(this._Item_56_4,[],compView_56);
    this._text_57 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_58 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_58,'item-left','');
    this.renderer.setElementAttribute(this._el_58,'name','ribbon');
    this.renderer.setElementAttribute(this._el_58,'role','img');
    this.renderer.setElementAttribute(this._el_58,'small','');
    this._Icon_58_3 = new import22.Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_58),this.renderer);
    this._text_59 = this.renderer.createText(this._el_58,' Populära just nu',(null as any));
    this._text_60 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_56_0.reset([]);
    this._Item_56_4.contentLabel = this._query_Label_56_0.first;
    compView_56.create(this._Item_56_4,[
      [].concat([this._el_58]),
      [],
      [].concat([
        this._text_57,
        this._text_60
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_61 = this.renderer.createText(this._el_53,'\n  ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_53,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','item item-block');
    this._appEl_62 = new import2.AppElement(62,53,this,this._el_62);
    var compView_62:any = import36.viewFactory_Item0(this.viewUtils,this.injector(62),this._appEl_62);
    this._Item_62_4 = new import20.Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_62),this.renderer);
    this._ItemContent_62_5 = new import20.ItemContent();
    this._query_Label_62_0 = new import21.QueryList<any>();
    this._query_Button_62_1 = new import21.QueryList<any>();
    this._query_Icon_62_2 = new import21.QueryList<any>();
    this._appEl_62.initComponent(this._Item_62_4,[],compView_62);
    this._text_63 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_64 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_64,'item-left','');
    this.renderer.setElementAttribute(this._el_64,'name','calendar');
    this.renderer.setElementAttribute(this._el_64,'role','img');
    this.renderer.setElementAttribute(this._el_64,'small','');
    this._Icon_64_3 = new import22.Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_64),this.renderer);
    this._text_65 = this.renderer.createText(this._el_64,' Nya tränare',(null as any));
    this._text_66 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_62_0.reset([]);
    this._Item_62_4.contentLabel = this._query_Label_62_0.first;
    compView_62.create(this._Item_62_4,[
      [].concat([this._el_64]),
      [],
      [].concat([
        this._text_63,
        this._text_66
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_67 = this.renderer.createText(this._el_53,'\n',(null as any));
    this._text_68 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    this._text_69 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_70 = this.renderer.createElement((null as any),'h5',(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'Categories',(null as any));
    this._text_72 = this.renderer.createText((null as any),'\n\n\n        ',(null as any));
    this._el_73 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_73_3 = new import17.Row();
    this._text_74 = this.renderer.createText(this._el_73,' \n        ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_73,'ion-col',(null as any));
    this._Col_75_3 = new import17.Col();
    this._text_76 = this.renderer.createText(this._el_75,'\n            ',(null as any));
    this._anchor_77 = this.renderer.createTemplateAnchor(this._el_75,(null as any));
    this._appEl_77 = new import2.AppElement(77,75,this,this._anchor_77);
    this._TemplateRef_77_5 = new import38.TemplateRef_(this._appEl_77,viewFactory_ExplorePage1);
    this._NgFor_77_6 = new import23.NgFor(this._appEl_77.vcRef,this._TemplateRef_77_5,this.parentInjector.get(import39.IterableDiffers),this.ref);
    this._text_78 = this.renderer.createText(this._el_75,'\n        ',(null as any));
    this._text_79 = this.renderer.createText(this._el_73,'\n        ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_73,'ion-col',(null as any));
    this._Col_80_3 = new import17.Col();
    this._text_81 = this.renderer.createText(this._el_80,'\n\n\n            ',(null as any));
    this._anchor_82 = this.renderer.createTemplateAnchor(this._el_80,(null as any));
    this._appEl_82 = new import2.AppElement(82,80,this,this._anchor_82);
    this._TemplateRef_82_5 = new import38.TemplateRef_(this._appEl_82,viewFactory_ExplorePage3);
    this._NgFor_82_6 = new import23.NgFor(this._appEl_82.vcRef,this._TemplateRef_82_5,this.parentInjector.get(import39.IterableDiffers),this.ref);
    this._text_83 = this.renderer.createText(this._el_80,'\n        ',(null as any));
    this._text_84 = this.renderer.createText(this._el_73,'\n        ',(null as any));
    this._text_85 = this.renderer.createText((null as any),'\n\n\n\n\n',(null as any));
    this._text_86 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    compView_10.create(this._Content_10_4,[
      [],
      [].concat([
        this._text_11,
        this._text_12,
        this._el_13,
        this._text_51,
        this._text_52,
        this._el_53,
        this._text_68,
        this._text_69,
        this._el_70,
        this._text_72,
        this._el_73,
        this._text_85,
        this._text_86
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_87 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_56,'click',this.eventHandler(this._handle_click_56_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_62,'click',this.eventHandler(this._handle_click_62_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._anchor_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._anchor_82,
      this._text_83,
      this._text_84,
      this._text_85,
      this._text_86,
      this._text_87
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4; }
    if (((token === import13.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4; }
    if (((token === import12.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3; }
    if (((token === import18.Card) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Card_19_3; }
    if (((token === import17.Col) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Col_17_3; }
    if (((token === import18.Card) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Card_30_3; }
    if (((token === import17.Col) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Col_28_3; }
    if (((token === import18.Card) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Card_41_3; }
    if (((token === import17.Col) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Col_39_3; }
    if (((token === import17.Row) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Row_15_3; }
    if (((token === import16.Scroll) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Scroll_13_4; }
    if (((token === import22.Icon) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._Icon_58_3; }
    if (((token === import20.Item) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Item_56_4; }
    if (((token === import20.ItemContent) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._ItemContent_56_5; }
    if (((token === import22.Icon) && ((64 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Icon_64_3; }
    if (((token === import20.Item) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Item_62_4; }
    if (((token === import20.ItemContent) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._ItemContent_62_5; }
    if (((token === import19.List) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._List_53_3; }
    if (((token === import38.TemplateRef) && (77 === requestNodeIndex))) { return this._TemplateRef_77_5; }
    if (((token === import23.NgFor) && (77 === requestNodeIndex))) { return this._NgFor_77_6; }
    if (((token === import17.Col) && ((75 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._Col_75_3; }
    if (((token === import38.TemplateRef) && (82 === requestNodeIndex))) { return this._TemplateRef_82_5; }
    if (((token === import23.NgFor) && (82 === requestNodeIndex))) { return this._NgFor_82_6; }
    if (((token === import17.Col) && ((80 <= requestNodeIndex) && (requestNodeIndex <= 83)))) { return this._Col_80_3; }
    if (((token === import17.Row) && ((73 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._Row_73_3; }
    if (((token === import15.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._Content_10_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_10_4.ngOnInit(); }
    changed = false;
    const currVal_3:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Scroll_13_4.scrollX = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_13.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Scroll_13_4.ngOnInit(); }
    const currVal_7:any = 'ribbon';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_58_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = 'calendar';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Icon_64_3.name = currVal_10;
      this._expr_10 = currVal_10;
    }
    changes = (null as any);
    const currVal_12:any = this.context.AllCategories;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgFor_77_6.ngForOf = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._NgFor_77_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_77_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_13:any = this.context.AllCategories;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgFor_82_6.ngForOf = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgFor_82_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_82_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_56_1.dirty) {
        this._query_Button_56_1.reset([]);
        this._Item_56_4._buttons = this._query_Button_56_1;
        this._query_Button_56_1.notifyOnChanges();
      }
      if (this._query_Icon_56_2.dirty) {
        this._query_Icon_56_2.reset([this._Icon_58_3]);
        this._Item_56_4._icons = this._query_Icon_56_2;
        this._query_Icon_56_2.notifyOnChanges();
      }
      if (this._query_Button_62_1.dirty) {
        this._query_Button_62_1.reset([]);
        this._Item_62_4._buttons = this._query_Button_62_1;
        this._query_Button_62_1.notifyOnChanges();
      }
      if (this._query_Icon_62_2.dirty) {
        this._query_Icon_62_2.reset([this._Icon_64_3]);
        this._Item_62_4._icons = this._query_Icon_62_2;
        this._query_Icon_62_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_56_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_62_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Scroll_13_4.scrollX;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_13,'scroll-x',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._Scroll_13_4.scrollY;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_13,'scroll-y',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._Icon_58_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_58,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._Icon_64_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_64,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_58_3.ngOnDestroy();
    this._Icon_64_3.ngOnDestroy();
    this._Content_10_4.ngOnDestroy();
  }
  private _handle_click_56_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context._popular()) !== false);
    return (true && pd_0);
  }
  private _handle_click_62_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context._newcoaches()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ExplorePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ExplorePage> {
  if ((renderType_ExplorePage === (null as any))) { (renderType_ExplorePage = viewUtils.createRenderComponentType('/Users/Perkka/booster/.tmp/pages/explore/explore.html',0,import10.ViewEncapsulation.None,styles_ExplorePage,{})); }
  return new _View_ExplorePage0(viewUtils,parentInjector,declarationEl);
}
class _View_ExplorePage1 extends import1.AppView<any> {
  _el_0:any;
  _Row_0_3:import17.Row;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import40.NgIf;
  _text_3:any;
  _arr_0:any;
  _arr_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ExplorePage1,renderType_ExplorePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_0_3 = new import17.Row();
    this._text_1 = this.renderer.createText(this._el_0,'\n\n\n                ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import38.TemplateRef_(this._appEl_2,viewFactory_ExplorePage2);
    this._NgIf_2_6 = new import40.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n\n            ',(null as any));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_1 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import40.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import17.Row) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Row_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = ((this.context.index % 2) === 0);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_2_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context._category(this._arr_0(this.context.$implicit.name),this._arr_1(this.context.$implicit.id))) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ExplorePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ExplorePage1(viewUtils,parentInjector,declarationEl);
}
class _View_ExplorePage2 extends import1.AppView<any> {
  _el_0:any;
  _Col_0_3:import17.Col;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import18.Card;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ExplorePage2,renderType_ExplorePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this._Col_0_3 = new import17.Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','backgound-for-categorys1');
    this._Card_2_3 = new import18.Card(this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'h2',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','card-title');
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_7,'src','img/2.jpg');
    this._text_8 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Card_2_3; }
    if (((token === import17.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Col_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ExplorePage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ExplorePage2(viewUtils,parentInjector,declarationEl);
}
class _View_ExplorePage3 extends import1.AppView<any> {
  _el_0:any;
  _Row_0_3:import17.Row;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import40.NgIf;
  _text_3:any;
  _arr_0:any;
  _arr_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ExplorePage3,renderType_ExplorePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_0_3 = new import17.Row();
    this._text_1 = this.renderer.createText(this._el_0,'\n\n\n                ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import38.TemplateRef_(this._appEl_2,viewFactory_ExplorePage4);
    this._NgIf_2_6 = new import40.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n\n            ',(null as any));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_1 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import40.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import17.Row) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Row_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = ((this.context.index % 2) === 1);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_2_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context._category(this._arr_0(this.context.$implicit.name),this._arr_1(this.context.$implicit.id))) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ExplorePage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ExplorePage3(viewUtils,parentInjector,declarationEl);
}
class _View_ExplorePage4 extends import1.AppView<any> {
  _el_0:any;
  _Col_0_3:import17.Col;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import18.Card;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ExplorePage4,renderType_ExplorePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this._Col_0_3 = new import17.Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','backgound-for-categorys2');
    this._Card_2_3 = new import18.Card(this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','card-title');
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'  \n                        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_7,'src','img/4.jpg');
    this._text_8 = this.renderer.createText(this._el_2,'    \n                    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Card_2_3; }
    if (((token === import17.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Col_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ExplorePage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ExplorePage4(viewUtils,parentInjector,declarationEl);
}